// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: announcements.scailo.proto

package sdk

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the available sort keys
type ANNOUNCEMENT_SORT_KEY int32

const (
	// Fetch ordered results by id
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED ANNOUNCEMENT_SORT_KEY = 0
	// Fetch ordered results by the creation timestamp
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_CREATED_AT ANNOUNCEMENT_SORT_KEY = 1
	// Fetch ordered results by the modified timestamp
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_MODIFIED_AT ANNOUNCEMENT_SORT_KEY = 2
	// Fetch ordered results by the approved on timestamp
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_APPROVED_ON ANNOUNCEMENT_SORT_KEY = 3
	// Fetch ordered results by the approved by field
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_APPROVED_BY ANNOUNCEMENT_SORT_KEY = 4
	// Fetch ordered results by the approver's role ID
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_APPROVER_ROLE_ID ANNOUNCEMENT_SORT_KEY = 5
	// Fetch ordered results by the approver's completed on timestamp
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_COMPLETED_ON ANNOUNCEMENT_SORT_KEY = 6
	// Fetch ordered results by the title
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_TITLE ANNOUNCEMENT_SORT_KEY = 10
	// Fetch ordered results by the description
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_DESCRIPTION ANNOUNCEMENT_SORT_KEY = 11
	// Fetch ordered results by the start on timestamp
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_START_ON ANNOUNCEMENT_SORT_KEY = 12
	// Fetch ordered results by the end on timestamp
	ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_END_ON ANNOUNCEMENT_SORT_KEY = 13
)

// Enum value maps for ANNOUNCEMENT_SORT_KEY.
var (
	ANNOUNCEMENT_SORT_KEY_name = map[int32]string{
		0:  "ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED",
		1:  "ANNOUNCEMENT_SORT_KEY_CREATED_AT",
		2:  "ANNOUNCEMENT_SORT_KEY_MODIFIED_AT",
		3:  "ANNOUNCEMENT_SORT_KEY_APPROVED_ON",
		4:  "ANNOUNCEMENT_SORT_KEY_APPROVED_BY",
		5:  "ANNOUNCEMENT_SORT_KEY_APPROVER_ROLE_ID",
		6:  "ANNOUNCEMENT_SORT_KEY_COMPLETED_ON",
		10: "ANNOUNCEMENT_SORT_KEY_TITLE",
		11: "ANNOUNCEMENT_SORT_KEY_DESCRIPTION",
		12: "ANNOUNCEMENT_SORT_KEY_START_ON",
		13: "ANNOUNCEMENT_SORT_KEY_END_ON",
	}
	ANNOUNCEMENT_SORT_KEY_value = map[string]int32{
		"ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED":   0,
		"ANNOUNCEMENT_SORT_KEY_CREATED_AT":       1,
		"ANNOUNCEMENT_SORT_KEY_MODIFIED_AT":      2,
		"ANNOUNCEMENT_SORT_KEY_APPROVED_ON":      3,
		"ANNOUNCEMENT_SORT_KEY_APPROVED_BY":      4,
		"ANNOUNCEMENT_SORT_KEY_APPROVER_ROLE_ID": 5,
		"ANNOUNCEMENT_SORT_KEY_COMPLETED_ON":     6,
		"ANNOUNCEMENT_SORT_KEY_TITLE":            10,
		"ANNOUNCEMENT_SORT_KEY_DESCRIPTION":      11,
		"ANNOUNCEMENT_SORT_KEY_START_ON":         12,
		"ANNOUNCEMENT_SORT_KEY_END_ON":           13,
	}
)

func (x ANNOUNCEMENT_SORT_KEY) Enum() *ANNOUNCEMENT_SORT_KEY {
	p := new(ANNOUNCEMENT_SORT_KEY)
	*p = x
	return p
}

func (x ANNOUNCEMENT_SORT_KEY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ANNOUNCEMENT_SORT_KEY) Descriptor() protoreflect.EnumDescriptor {
	return file_announcements_scailo_proto_enumTypes[0].Descriptor()
}

func (ANNOUNCEMENT_SORT_KEY) Type() protoreflect.EnumType {
	return &file_announcements_scailo_proto_enumTypes[0]
}

func (x ANNOUNCEMENT_SORT_KEY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ANNOUNCEMENT_SORT_KEY.Descriptor instead.
func (ANNOUNCEMENT_SORT_KEY) EnumDescriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{0}
}

// Describes the parameters necessary to create a record
type AnnouncementsServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores a globally unique entity UUID. This will be set at the organization level
	EntityUuid string `protobuf:"bytes,1,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// Stores any comment that the user might add during this operation
	UserComment string `protobuf:"bytes,2,opt,name=user_comment,json=userComment,proto3" json:"user_comment,omitempty"`
	// The associated vault folder ID
	VaultFolderId uint64 `protobuf:"varint,9,opt,name=vault_folder_id,json=vaultFolderId,proto3" json:"vault_folder_id,omitempty"`
	// The title of the announcement
	Title string `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	// The description of the announcement
	Description string `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	// The start timestamp
	StartOn uint64 `protobuf:"varint,12,opt,name=start_on,json=startOn,proto3" json:"start_on,omitempty"`
	// The end timestamp
	EndOn         uint64 `protobuf:"varint,13,opt,name=end_on,json=endOn,proto3" json:"end_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServiceCreateRequest) Reset() {
	*x = AnnouncementsServiceCreateRequest{}
	mi := &file_announcements_scailo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServiceCreateRequest) ProtoMessage() {}

func (x *AnnouncementsServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*AnnouncementsServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{0}
}

func (x *AnnouncementsServiceCreateRequest) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *AnnouncementsServiceCreateRequest) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *AnnouncementsServiceCreateRequest) GetVaultFolderId() uint64 {
	if x != nil {
		return x.VaultFolderId
	}
	return 0
}

func (x *AnnouncementsServiceCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementsServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnnouncementsServiceCreateRequest) GetStartOn() uint64 {
	if x != nil {
		return x.StartOn
	}
	return 0
}

func (x *AnnouncementsServiceCreateRequest) GetEndOn() uint64 {
	if x != nil {
		return x.EndOn
	}
	return 0
}

// Describes the parameters necessary to update a record
type AnnouncementsServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores any comment that the user might add during this operation
	UserComment string `protobuf:"bytes,1,opt,name=user_comment,json=userComment,proto3" json:"user_comment,omitempty"`
	// The ID of the record that needs to be updated
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
	NotifyUsers bool `protobuf:"varint,3,opt,name=notify_users,json=notifyUsers,proto3" json:"notify_users,omitempty"`
	// The associated vault folder ID
	VaultFolderId uint64 `protobuf:"varint,9,opt,name=vault_folder_id,json=vaultFolderId,proto3" json:"vault_folder_id,omitempty"`
	// The title of the announcement
	Title string `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	// The description of the announcement
	Description string `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	// The start timestamp
	StartOn uint64 `protobuf:"varint,12,opt,name=start_on,json=startOn,proto3" json:"start_on,omitempty"`
	// The end timestamp
	EndOn         uint64 `protobuf:"varint,13,opt,name=end_on,json=endOn,proto3" json:"end_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServiceUpdateRequest) Reset() {
	*x = AnnouncementsServiceUpdateRequest{}
	mi := &file_announcements_scailo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServiceUpdateRequest) ProtoMessage() {}

func (x *AnnouncementsServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*AnnouncementsServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{1}
}

func (x *AnnouncementsServiceUpdateRequest) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *AnnouncementsServiceUpdateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnnouncementsServiceUpdateRequest) GetNotifyUsers() bool {
	if x != nil {
		return x.NotifyUsers
	}
	return false
}

func (x *AnnouncementsServiceUpdateRequest) GetVaultFolderId() uint64 {
	if x != nil {
		return x.VaultFolderId
	}
	return 0
}

func (x *AnnouncementsServiceUpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementsServiceUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnnouncementsServiceUpdateRequest) GetStartOn() uint64 {
	if x != nil {
		return x.StartOn
	}
	return 0
}

func (x *AnnouncementsServiceUpdateRequest) GetEndOn() uint64 {
	if x != nil {
		return x.EndOn
	}
	return 0
}

// Describes the parameters that are part of a standard response
type Announcement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores a globally unique entity UUID. This will be set at the organization level
	EntityUuid string `protobuf:"bytes,1,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// Stores the metadata of this announcement
	Metadata *EmployeeMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Stores the approval metadata
	ApprovalMetadata *ApprovalMetadata `protobuf:"bytes,3,opt,name=approval_metadata,json=approvalMetadata,proto3" json:"approval_metadata,omitempty"`
	// The status of this announcement
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,4,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// Stores the logs of every operation performed on this announcement
	Logs []*LogbookLogConciseSLC `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	// The timestamp of when this announcement was marked as completed
	CompletedOn uint64 `protobuf:"varint,6,opt,name=completed_on,json=completedOn,proto3" json:"completed_on,omitempty"`
	// The associated vault folder ID
	VaultFolderId uint64 `protobuf:"varint,9,opt,name=vault_folder_id,json=vaultFolderId,proto3" json:"vault_folder_id,omitempty"`
	// The title of the announcement
	Title string `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	// The description of the announcement
	Description string `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	// The start timestamp
	StartOn uint64 `protobuf:"varint,12,opt,name=start_on,json=startOn,proto3" json:"start_on,omitempty"`
	// The end timestamp
	EndOn         uint64 `protobuf:"varint,13,opt,name=end_on,json=endOn,proto3" json:"end_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_announcements_scailo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{2}
}

func (x *Announcement) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *Announcement) GetMetadata() *EmployeeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Announcement) GetApprovalMetadata() *ApprovalMetadata {
	if x != nil {
		return x.ApprovalMetadata
	}
	return nil
}

func (x *Announcement) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *Announcement) GetLogs() []*LogbookLogConciseSLC {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Announcement) GetCompletedOn() uint64 {
	if x != nil {
		return x.CompletedOn
	}
	return 0
}

func (x *Announcement) GetVaultFolderId() uint64 {
	if x != nil {
		return x.VaultFolderId
	}
	return 0
}

func (x *Announcement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Announcement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Announcement) GetStartOn() uint64 {
	if x != nil {
		return x.StartOn
	}
	return 0
}

func (x *Announcement) GetEndOn() uint64 {
	if x != nil {
		return x.EndOn
	}
	return 0
}

// Describes the message consisting of the list of records
type AnnouncementsList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of records
	List          []*Announcement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsList) Reset() {
	*x = AnnouncementsList{}
	mi := &file_announcements_scailo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsList) ProtoMessage() {}

func (x *AnnouncementsList) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsList.ProtoReflect.Descriptor instead.
func (*AnnouncementsList) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{3}
}

func (x *AnnouncementsList) GetList() []*Announcement {
	if x != nil {
		return x.List
	}
	return nil
}

// Describes a pagination request to retrieve records
type AnnouncementsServicePaginationReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The number of records that need to be sent in the response
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// The number that need to be offset by before fetching the records
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The sort order that is to be used to fetch the pagination response
	SortOrder SORT_ORDER `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=Scailo.SORT_ORDER" json:"sort_order,omitempty"`
	// The sort key that is to be used to fetch the pagination response
	SortKey ANNOUNCEMENT_SORT_KEY `protobuf:"varint,5,opt,name=sort_key,json=sortKey,proto3,enum=Scailo.ANNOUNCEMENT_SORT_KEY" json:"sort_key,omitempty"`
	// The status of this announcement
	Status        STANDARD_LIFECYCLE_STATUS `protobuf:"varint,6,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServicePaginationReq) Reset() {
	*x = AnnouncementsServicePaginationReq{}
	mi := &file_announcements_scailo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServicePaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServicePaginationReq) ProtoMessage() {}

func (x *AnnouncementsServicePaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServicePaginationReq.ProtoReflect.Descriptor instead.
func (*AnnouncementsServicePaginationReq) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{4}
}

func (x *AnnouncementsServicePaginationReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *AnnouncementsServicePaginationReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AnnouncementsServicePaginationReq) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AnnouncementsServicePaginationReq) GetSortOrder() SORT_ORDER {
	if x != nil {
		return x.SortOrder
	}
	return SORT_ORDER_ASCENDING_UNSPECIFIED
}

func (x *AnnouncementsServicePaginationReq) GetSortKey() ANNOUNCEMENT_SORT_KEY {
	if x != nil {
		return x.SortKey
	}
	return ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED
}

func (x *AnnouncementsServicePaginationReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

// Describes the response to a pagination request
type AnnouncementsServicePaginationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of records in this payload
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// The number that has been offset before fetching the records. This is the same value that has been sent as part of the pagination request
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The total number of records that are available
	Total uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// The list of records
	Payload       []*Announcement `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServicePaginationResponse) Reset() {
	*x = AnnouncementsServicePaginationResponse{}
	mi := &file_announcements_scailo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServicePaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServicePaginationResponse) ProtoMessage() {}

func (x *AnnouncementsServicePaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServicePaginationResponse.ProtoReflect.Descriptor instead.
func (*AnnouncementsServicePaginationResponse) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{5}
}

func (x *AnnouncementsServicePaginationResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AnnouncementsServicePaginationResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AnnouncementsServicePaginationResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AnnouncementsServicePaginationResponse) GetPayload() []*Announcement {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Describes the base request payload of a filter search
type AnnouncementsServiceFilterReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The number of records that need to be sent in the response. Returns all records if it is set to -1
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// The number that need to be offset by before fetching the records
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The sort order that is to be used to fetch the pagination response
	SortOrder SORT_ORDER `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=Scailo.SORT_ORDER" json:"sort_order,omitempty"`
	// The sort key that is to be used to fetch the pagination response
	SortKey ANNOUNCEMENT_SORT_KEY `protobuf:"varint,5,opt,name=sort_key,json=sortKey,proto3,enum=Scailo.ANNOUNCEMENT_SORT_KEY" json:"sort_key,omitempty"`
	// The minimum timestamp that needs to be considered to filter by creation
	CreationTimestampStart uint64 `protobuf:"varint,101,opt,name=creation_timestamp_start,json=creationTimestampStart,proto3" json:"creation_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by creation
	CreationTimestampEnd uint64 `protobuf:"varint,102,opt,name=creation_timestamp_end,json=creationTimestampEnd,proto3" json:"creation_timestamp_end,omitempty"`
	// The minimum timestamp that needs to be considered to filter by modification
	ModificationTimestampStart uint64 `protobuf:"varint,103,opt,name=modification_timestamp_start,json=modificationTimestampStart,proto3" json:"modification_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by modification
	ModificationTimestampEnd uint64 `protobuf:"varint,104,opt,name=modification_timestamp_end,json=modificationTimestampEnd,proto3" json:"modification_timestamp_end,omitempty"`
	// The entity UUID that is to be used to filter records
	EntityUuid string `protobuf:"bytes,8,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// The status of this announcement
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,10,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// The start range of approved timestamp
	ApprovedOnStart uint64 `protobuf:"varint,11,opt,name=approved_on_start,json=approvedOnStart,proto3" json:"approved_on_start,omitempty"`
	// The end range of approved timestamp
	ApprovedOnEnd uint64 `protobuf:"varint,12,opt,name=approved_on_end,json=approvedOnEnd,proto3" json:"approved_on_end,omitempty"`
	// The ID of the approver
	ApprovedByUserId uint64 `protobuf:"varint,13,opt,name=approved_by_user_id,json=approvedByUserId,proto3" json:"approved_by_user_id,omitempty"`
	// The role ID of the approver
	ApproverRoleId uint64 `protobuf:"varint,14,opt,name=approver_role_id,json=approverRoleId,proto3" json:"approver_role_id,omitempty"`
	// The start range of completed timestamp
	CompletedOnStart uint64 `protobuf:"varint,15,opt,name=completed_on_start,json=completedOnStart,proto3" json:"completed_on_start,omitempty"`
	// The end range of completed timestamp
	CompletedOnEnd uint64 `protobuf:"varint,16,opt,name=completed_on_end,json=completedOnEnd,proto3" json:"completed_on_end,omitempty"`
	// The title of the announcement
	Title string `protobuf:"bytes,20,opt,name=title,proto3" json:"title,omitempty"`
	// The description of the announcement
	Description string `protobuf:"bytes,21,opt,name=description,proto3" json:"description,omitempty"`
	// The start range of start timestamp
	StartOnStart uint64 `protobuf:"varint,22,opt,name=start_on_start,json=startOnStart,proto3" json:"start_on_start,omitempty"`
	// The end range of start timestamp
	StartOnEnd uint64 `protobuf:"varint,23,opt,name=start_on_end,json=startOnEnd,proto3" json:"start_on_end,omitempty"`
	// The start range of end timestamp
	EndOnStart uint64 `protobuf:"varint,24,opt,name=end_on_start,json=endOnStart,proto3" json:"end_on_start,omitempty"`
	// The end range of end timestamp
	EndOnEnd      uint64 `protobuf:"varint,25,opt,name=end_on_end,json=endOnEnd,proto3" json:"end_on_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServiceFilterReq) Reset() {
	*x = AnnouncementsServiceFilterReq{}
	mi := &file_announcements_scailo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServiceFilterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServiceFilterReq) ProtoMessage() {}

func (x *AnnouncementsServiceFilterReq) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServiceFilterReq.ProtoReflect.Descriptor instead.
func (*AnnouncementsServiceFilterReq) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{6}
}

func (x *AnnouncementsServiceFilterReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *AnnouncementsServiceFilterReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetSortOrder() SORT_ORDER {
	if x != nil {
		return x.SortOrder
	}
	return SORT_ORDER_ASCENDING_UNSPECIFIED
}

func (x *AnnouncementsServiceFilterReq) GetSortKey() ANNOUNCEMENT_SORT_KEY {
	if x != nil {
		return x.SortKey
	}
	return ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED
}

func (x *AnnouncementsServiceFilterReq) GetCreationTimestampStart() uint64 {
	if x != nil {
		return x.CreationTimestampStart
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetCreationTimestampEnd() uint64 {
	if x != nil {
		return x.CreationTimestampEnd
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetModificationTimestampStart() uint64 {
	if x != nil {
		return x.ModificationTimestampStart
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetModificationTimestampEnd() uint64 {
	if x != nil {
		return x.ModificationTimestampEnd
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *AnnouncementsServiceFilterReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *AnnouncementsServiceFilterReq) GetApprovedOnStart() uint64 {
	if x != nil {
		return x.ApprovedOnStart
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetApprovedOnEnd() uint64 {
	if x != nil {
		return x.ApprovedOnEnd
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetApprovedByUserId() uint64 {
	if x != nil {
		return x.ApprovedByUserId
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetApproverRoleId() uint64 {
	if x != nil {
		return x.ApproverRoleId
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetCompletedOnStart() uint64 {
	if x != nil {
		return x.CompletedOnStart
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetCompletedOnEnd() uint64 {
	if x != nil {
		return x.CompletedOnEnd
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementsServiceFilterReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnnouncementsServiceFilterReq) GetStartOnStart() uint64 {
	if x != nil {
		return x.StartOnStart
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetStartOnEnd() uint64 {
	if x != nil {
		return x.StartOnEnd
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetEndOnStart() uint64 {
	if x != nil {
		return x.EndOnStart
	}
	return 0
}

func (x *AnnouncementsServiceFilterReq) GetEndOnEnd() uint64 {
	if x != nil {
		return x.EndOnEnd
	}
	return 0
}

// Describes the base request payload of a count search
type AnnouncementsServiceCountReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The minimum timestamp that needs to be considered to filter by creation
	CreationTimestampStart uint64 `protobuf:"varint,101,opt,name=creation_timestamp_start,json=creationTimestampStart,proto3" json:"creation_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by creation
	CreationTimestampEnd uint64 `protobuf:"varint,102,opt,name=creation_timestamp_end,json=creationTimestampEnd,proto3" json:"creation_timestamp_end,omitempty"`
	// The minimum timestamp that needs to be considered to filter by modification
	ModificationTimestampStart uint64 `protobuf:"varint,103,opt,name=modification_timestamp_start,json=modificationTimestampStart,proto3" json:"modification_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by modification
	ModificationTimestampEnd uint64 `protobuf:"varint,104,opt,name=modification_timestamp_end,json=modificationTimestampEnd,proto3" json:"modification_timestamp_end,omitempty"`
	// The entity UUID that is to be used to filter records
	EntityUuid string `protobuf:"bytes,8,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// The status of this announcement
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,10,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// The start range of approved timestamp
	ApprovedOnStart uint64 `protobuf:"varint,11,opt,name=approved_on_start,json=approvedOnStart,proto3" json:"approved_on_start,omitempty"`
	// The end range of approved timestamp
	ApprovedOnEnd uint64 `protobuf:"varint,12,opt,name=approved_on_end,json=approvedOnEnd,proto3" json:"approved_on_end,omitempty"`
	// The ID of the approver
	ApprovedByUserId uint64 `protobuf:"varint,13,opt,name=approved_by_user_id,json=approvedByUserId,proto3" json:"approved_by_user_id,omitempty"`
	// The role ID of the approver
	ApproverRoleId uint64 `protobuf:"varint,14,opt,name=approver_role_id,json=approverRoleId,proto3" json:"approver_role_id,omitempty"`
	// The start range of completed timestamp
	CompletedOnStart uint64 `protobuf:"varint,15,opt,name=completed_on_start,json=completedOnStart,proto3" json:"completed_on_start,omitempty"`
	// The end range of completed timestamp
	CompletedOnEnd uint64 `protobuf:"varint,16,opt,name=completed_on_end,json=completedOnEnd,proto3" json:"completed_on_end,omitempty"`
	// The title of the announcement
	Title string `protobuf:"bytes,20,opt,name=title,proto3" json:"title,omitempty"`
	// The description of the announcement
	Description string `protobuf:"bytes,21,opt,name=description,proto3" json:"description,omitempty"`
	// The start range of start timestamp
	StartOnStart uint64 `protobuf:"varint,22,opt,name=start_on_start,json=startOnStart,proto3" json:"start_on_start,omitempty"`
	// The end range of start timestamp
	StartOnEnd uint64 `protobuf:"varint,23,opt,name=start_on_end,json=startOnEnd,proto3" json:"start_on_end,omitempty"`
	// The start range of end timestamp
	EndOnStart uint64 `protobuf:"varint,24,opt,name=end_on_start,json=endOnStart,proto3" json:"end_on_start,omitempty"`
	// The end range of end timestamp
	EndOnEnd      uint64 `protobuf:"varint,25,opt,name=end_on_end,json=endOnEnd,proto3" json:"end_on_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServiceCountReq) Reset() {
	*x = AnnouncementsServiceCountReq{}
	mi := &file_announcements_scailo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServiceCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServiceCountReq) ProtoMessage() {}

func (x *AnnouncementsServiceCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServiceCountReq.ProtoReflect.Descriptor instead.
func (*AnnouncementsServiceCountReq) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{7}
}

func (x *AnnouncementsServiceCountReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *AnnouncementsServiceCountReq) GetCreationTimestampStart() uint64 {
	if x != nil {
		return x.CreationTimestampStart
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetCreationTimestampEnd() uint64 {
	if x != nil {
		return x.CreationTimestampEnd
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetModificationTimestampStart() uint64 {
	if x != nil {
		return x.ModificationTimestampStart
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetModificationTimestampEnd() uint64 {
	if x != nil {
		return x.ModificationTimestampEnd
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *AnnouncementsServiceCountReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *AnnouncementsServiceCountReq) GetApprovedOnStart() uint64 {
	if x != nil {
		return x.ApprovedOnStart
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetApprovedOnEnd() uint64 {
	if x != nil {
		return x.ApprovedOnEnd
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetApprovedByUserId() uint64 {
	if x != nil {
		return x.ApprovedByUserId
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetApproverRoleId() uint64 {
	if x != nil {
		return x.ApproverRoleId
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetCompletedOnStart() uint64 {
	if x != nil {
		return x.CompletedOnStart
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetCompletedOnEnd() uint64 {
	if x != nil {
		return x.CompletedOnEnd
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementsServiceCountReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnnouncementsServiceCountReq) GetStartOnStart() uint64 {
	if x != nil {
		return x.StartOnStart
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetStartOnEnd() uint64 {
	if x != nil {
		return x.StartOnEnd
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetEndOnStart() uint64 {
	if x != nil {
		return x.EndOnStart
	}
	return 0
}

func (x *AnnouncementsServiceCountReq) GetEndOnEnd() uint64 {
	if x != nil {
		return x.EndOnEnd
	}
	return 0
}

// Describes the request payload for performing a generic search operation on records
type AnnouncementsServiceSearchAllReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The number of records that need to be sent in the response. Returns all records if it is set to -1
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// The number that need to be offset by before fetching the records
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The sort order that is to be used to fetch the pagination response
	SortOrder SORT_ORDER `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=Scailo.SORT_ORDER" json:"sort_order,omitempty"`
	// The sort key that is to be used to fetch the pagination response
	SortKey ANNOUNCEMENT_SORT_KEY `protobuf:"varint,5,opt,name=sort_key,json=sortKey,proto3,enum=Scailo.ANNOUNCEMENT_SORT_KEY" json:"sort_key,omitempty"`
	// The entity UUID that is to be used to filter records
	EntityUuid string `protobuf:"bytes,6,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// Limit the search space to the given status
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,10,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// Describes the key with which the search operation needs to be performed
	SearchKey     string `protobuf:"bytes,11,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementsServiceSearchAllReq) Reset() {
	*x = AnnouncementsServiceSearchAllReq{}
	mi := &file_announcements_scailo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementsServiceSearchAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementsServiceSearchAllReq) ProtoMessage() {}

func (x *AnnouncementsServiceSearchAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_scailo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementsServiceSearchAllReq.ProtoReflect.Descriptor instead.
func (*AnnouncementsServiceSearchAllReq) Descriptor() ([]byte, []int) {
	return file_announcements_scailo_proto_rawDescGZIP(), []int{8}
}

func (x *AnnouncementsServiceSearchAllReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *AnnouncementsServiceSearchAllReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AnnouncementsServiceSearchAllReq) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AnnouncementsServiceSearchAllReq) GetSortOrder() SORT_ORDER {
	if x != nil {
		return x.SortOrder
	}
	return SORT_ORDER_ASCENDING_UNSPECIFIED
}

func (x *AnnouncementsServiceSearchAllReq) GetSortKey() ANNOUNCEMENT_SORT_KEY {
	if x != nil {
		return x.SortKey
	}
	return ANNOUNCEMENT_SORT_KEY_ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED
}

func (x *AnnouncementsServiceSearchAllReq) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *AnnouncementsServiceSearchAllReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *AnnouncementsServiceSearchAllReq) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

var File_announcements_scailo_proto protoreflect.FileDescriptor

const file_announcements_scailo_proto_rawDesc = "" +
	"\n" +
	"\x1aannouncements.scailo.proto\x12\x06Scailo\x1a\x11base.scailo.proto\x1a\x1bbuf/validate/validate.proto\"\xc2\x02\n" +
	"!AnnouncementsServiceCreateRequest\x12\x1f\n" +
	"\ventity_uuid\x18\x01 \x01(\tR\n" +
	"entityUuid\x12!\n" +
	"\fuser_comment\x18\x02 \x01(\tR\vuserComment\x12/\n" +
	"\x0fvault_folder_id\x18\t \x01(\x04B\a\xbaH\x042\x02(\x00R\rvaultFolderId\x12+\n" +
	"\x05title\x18\n" +
	" \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]+$R\x05title\x127\n" +
	"\vdescription\x18\v \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]+$R\vdescription\x12\"\n" +
	"\bstart_on\x18\f \x01(\x04B\a\xbaH\x042\x02(\x00R\astartOn\x12\x1e\n" +
	"\x06end_on\x18\r \x01(\x04B\a\xbaH\x042\x02(\x00R\x05endOn\"\xdd\x02\n" +
	"!AnnouncementsServiceUpdateRequest\x12!\n" +
	"\fuser_comment\x18\x01 \x01(\tR\vuserComment\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x02id\x12!\n" +
	"\fnotify_users\x18\x03 \x01(\bR\vnotifyUsers\x12/\n" +
	"\x0fvault_folder_id\x18\t \x01(\x04B\a\xbaH\x042\x02(\x00R\rvaultFolderId\x12+\n" +
	"\x05title\x18\n" +
	" \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]+$R\x05title\x127\n" +
	"\vdescription\x18\v \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]+$R\vdescription\x12\"\n" +
	"\bstart_on\x18\f \x01(\x04B\a\xbaH\x042\x02(\x00R\astartOn\x12\x1e\n" +
	"\x06end_on\x18\r \x01(\x04B\a\xbaH\x042\x02(\x00R\x05endOn\"\xce\x03\n" +
	"\fAnnouncement\x12\x1f\n" +
	"\ventity_uuid\x18\x01 \x01(\tR\n" +
	"entityUuid\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x18.Scailo.EmployeeMetadataR\bmetadata\x12E\n" +
	"\x11approval_metadata\x18\x03 \x01(\v2\x18.Scailo.ApprovalMetadataR\x10approvalMetadata\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x120\n" +
	"\x04logs\x18\x05 \x03(\v2\x1c.Scailo.LogbookLogConciseSLCR\x04logs\x12!\n" +
	"\fcompleted_on\x18\x06 \x01(\x04R\vcompletedOn\x12&\n" +
	"\x0fvault_folder_id\x18\t \x01(\x04R\rvaultFolderId\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x19\n" +
	"\bstart_on\x18\f \x01(\x04R\astartOn\x12\x15\n" +
	"\x06end_on\x18\r \x01(\x04R\x05endOn\"=\n" +
	"\x11AnnouncementsList\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.Scailo.AnnouncementR\x04list\"\xbd\x02\n" +
	"!AnnouncementsServicePaginationReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x12\x1d\n" +
	"\x05count\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x05count\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\x121\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x12.Scailo.SORT_ORDERR\tsortOrder\x128\n" +
	"\bsort_key\x18\x05 \x01(\x0e2\x1d.Scailo.ANNOUNCEMENT_SORT_KEYR\asortKey\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\"\x9c\x01\n" +
	"&AnnouncementsServicePaginationResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12.\n" +
	"\apayload\x18\x04 \x03(\v2\x14.Scailo.AnnouncementR\apayload\"\x98\b\n" +
	"\x1dAnnouncementsServiceFilterReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x12&\n" +
	"\x05count\x18\x02 \x01(\x03B\x10\xbaH\r\"\v(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x05count\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\x121\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x12.Scailo.SORT_ORDERR\tsortOrder\x128\n" +
	"\bsort_key\x18\x05 \x01(\x0e2\x1d.Scailo.ANNOUNCEMENT_SORT_KEYR\asortKey\x128\n" +
	"\x18creation_timestamp_start\x18e \x01(\x04R\x16creationTimestampStart\x124\n" +
	"\x16creation_timestamp_end\x18f \x01(\x04R\x14creationTimestampEnd\x12@\n" +
	"\x1cmodification_timestamp_start\x18g \x01(\x04R\x1amodificationTimestampStart\x12<\n" +
	"\x1amodification_timestamp_end\x18h \x01(\x04R\x18modificationTimestampEnd\x12\x1f\n" +
	"\ventity_uuid\x18\b \x01(\tR\n" +
	"entityUuid\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x12*\n" +
	"\x11approved_on_start\x18\v \x01(\x04R\x0fapprovedOnStart\x12&\n" +
	"\x0fapproved_on_end\x18\f \x01(\x04R\rapprovedOnEnd\x12-\n" +
	"\x13approved_by_user_id\x18\r \x01(\x04R\x10approvedByUserId\x12(\n" +
	"\x10approver_role_id\x18\x0e \x01(\x04R\x0eapproverRoleId\x12,\n" +
	"\x12completed_on_start\x18\x0f \x01(\x04R\x10completedOnStart\x12(\n" +
	"\x10completed_on_end\x18\x10 \x01(\x04R\x0ecompletedOnEnd\x12\x14\n" +
	"\x05title\x18\x14 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x15 \x01(\tR\vdescription\x12$\n" +
	"\x0estart_on_start\x18\x16 \x01(\x04R\fstartOnStart\x12 \n" +
	"\fstart_on_end\x18\x17 \x01(\x04R\n" +
	"startOnEnd\x12 \n" +
	"\fend_on_start\x18\x18 \x01(\x04R\n" +
	"endOnStart\x12\x1c\n" +
	"\n" +
	"end_on_end\x18\x19 \x01(\x04R\bendOnEnd\"\xe1\x06\n" +
	"\x1cAnnouncementsServiceCountReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x128\n" +
	"\x18creation_timestamp_start\x18e \x01(\x04R\x16creationTimestampStart\x124\n" +
	"\x16creation_timestamp_end\x18f \x01(\x04R\x14creationTimestampEnd\x12@\n" +
	"\x1cmodification_timestamp_start\x18g \x01(\x04R\x1amodificationTimestampStart\x12<\n" +
	"\x1amodification_timestamp_end\x18h \x01(\x04R\x18modificationTimestampEnd\x12\x1f\n" +
	"\ventity_uuid\x18\b \x01(\tR\n" +
	"entityUuid\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x12*\n" +
	"\x11approved_on_start\x18\v \x01(\x04R\x0fapprovedOnStart\x12&\n" +
	"\x0fapproved_on_end\x18\f \x01(\x04R\rapprovedOnEnd\x12-\n" +
	"\x13approved_by_user_id\x18\r \x01(\x04R\x10approvedByUserId\x12(\n" +
	"\x10approver_role_id\x18\x0e \x01(\x04R\x0eapproverRoleId\x12,\n" +
	"\x12completed_on_start\x18\x0f \x01(\x04R\x10completedOnStart\x12(\n" +
	"\x10completed_on_end\x18\x10 \x01(\x04R\x0ecompletedOnEnd\x12\x14\n" +
	"\x05title\x18\x14 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x15 \x01(\tR\vdescription\x12$\n" +
	"\x0estart_on_start\x18\x16 \x01(\x04R\fstartOnStart\x12 \n" +
	"\fstart_on_end\x18\x17 \x01(\x04R\n" +
	"startOnEnd\x12 \n" +
	"\fend_on_start\x18\x18 \x01(\x04R\n" +
	"endOnStart\x12\x1c\n" +
	"\n" +
	"end_on_end\x18\x19 \x01(\x04R\bendOnEnd\"\x85\x03\n" +
	" AnnouncementsServiceSearchAllReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x12&\n" +
	"\x05count\x18\x02 \x01(\x03B\x10\xbaH\r\"\v(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x05count\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\x121\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x12.Scailo.SORT_ORDERR\tsortOrder\x128\n" +
	"\bsort_key\x18\x05 \x01(\x0e2\x1d.Scailo.ANNOUNCEMENT_SORT_KEYR\asortKey\x12\x1f\n" +
	"\ventity_uuid\x18\x06 \x01(\tR\n" +
	"entityUuid\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x12\x1d\n" +
	"\n" +
	"search_key\x18\v \x01(\tR\tsearchKey*\xbe\x03\n" +
	"\x15ANNOUNCEMENT_SORT_KEY\x12(\n" +
	"$ANNOUNCEMENT_SORT_KEY_ID_UNSPECIFIED\x10\x00\x12$\n" +
	" ANNOUNCEMENT_SORT_KEY_CREATED_AT\x10\x01\x12%\n" +
	"!ANNOUNCEMENT_SORT_KEY_MODIFIED_AT\x10\x02\x12%\n" +
	"!ANNOUNCEMENT_SORT_KEY_APPROVED_ON\x10\x03\x12%\n" +
	"!ANNOUNCEMENT_SORT_KEY_APPROVED_BY\x10\x04\x12*\n" +
	"&ANNOUNCEMENT_SORT_KEY_APPROVER_ROLE_ID\x10\x05\x12&\n" +
	"\"ANNOUNCEMENT_SORT_KEY_COMPLETED_ON\x10\x06\x12\x1f\n" +
	"\x1bANNOUNCEMENT_SORT_KEY_TITLE\x10\n" +
	"\x12%\n" +
	"!ANNOUNCEMENT_SORT_KEY_DESCRIPTION\x10\v\x12\"\n" +
	"\x1eANNOUNCEMENT_SORT_KEY_START_ON\x10\f\x12 \n" +
	"\x1cANNOUNCEMENT_SORT_KEY_END_ON\x10\r2\xf5\x10\n" +
	"\x14AnnouncementsService\x12O\n" +
	"\x06Create\x12).Scailo.AnnouncementsServiceCreateRequest\x1a\x1a.Scailo.IdentifierResponse\x12N\n" +
	"\x05Draft\x12).Scailo.AnnouncementsServiceCreateRequest\x1a\x1a.Scailo.IdentifierResponse\x12T\n" +
	"\vDraftUpdate\x12).Scailo.AnnouncementsServiceUpdateRequest\x1a\x1a.Scailo.IdentifierResponse\x12X\n" +
	"\x13SendForVerification\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12K\n" +
	"\x06Verify\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\aApprove\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12T\n" +
	"\x0fSendForRevision\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12W\n" +
	"\x0eRevisionUpdate\x12).Scailo.AnnouncementsServiceUpdateRequest\x1a\x1a.Scailo.IdentifierResponse\x12I\n" +
	"\x04Halt\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\aDiscard\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\aRestore\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12M\n" +
	"\bComplete\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12K\n" +
	"\x06Repeat\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12O\n" +
	"\n" +
	"CommentAdd\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x124\n" +
	"\bViewByID\x12\x12.Scailo.Identifier\x1a\x14.Scailo.Announcement\x12:\n" +
	"\n" +
	"ViewByUUID\x12\x16.Scailo.IdentifierUUID\x1a\x14.Scailo.Announcement\x12=\n" +
	"\x11ViewEssentialByID\x12\x12.Scailo.Identifier\x1a\x14.Scailo.Announcement\x12C\n" +
	"\x13ViewEssentialByUUID\x12\x16.Scailo.IdentifierUUID\x1a\x14.Scailo.Announcement\x12A\n" +
	"\vViewFromIDs\x12\x17.Scailo.IdentifiersList\x1a\x19.Scailo.AnnouncementsList\x12:\n" +
	"\aViewAll\x12\x14.Scailo.ActiveStatus\x1a\x19.Scailo.AnnouncementsList\x12I\n" +
	"\x14ViewAllForEntityUUID\x12\x16.Scailo.IdentifierUUID\x1a\x19.Scailo.AnnouncementsList\x12o\n" +
	"\x12ViewWithPagination\x12).Scailo.AnnouncementsServicePaginationReq\x1a..Scailo.AnnouncementsServicePaginationResponse\x12P\n" +
	"\tSearchAll\x12(.Scailo.AnnouncementsServiceSearchAllReq\x1a\x19.Scailo.AnnouncementsList\x12J\n" +
	"\x06Filter\x12%.Scailo.AnnouncementsServiceFilterReq\x1a\x19.Scailo.AnnouncementsList\x12G\n" +
	"\rCountInStatus\x12\x1f.Scailo.CountInSLCStatusRequest\x1a\x15.Scailo.CountResponse\x12D\n" +
	"\x05Count\x12$.Scailo.AnnouncementsServiceCountReq\x1a\x15.Scailo.CountResponse\x12L\n" +
	"\rDownloadAsCSV\x12%.Scailo.AnnouncementsServiceFilterReq\x1a\x14.Scailo.StandardFile\x12B\n" +
	"\rImportFromCSV\x12\x14.Scailo.StandardFile\x1a\x1b.Scailo.IdentifierUUIDsListBj\n" +
	"\n" +
	"com.ScailoB\x18AnnouncementsScailoProtoP\x01Z\n" +
	"Scailo/sdk\xa2\x02\x03SXX\xaa\x02\x06Scailo\xca\x02\x06Scailo\xe2\x02\x12Scailo\\GPBMetadata\xea\x02\x06Scailob\x06proto3"

var (
	file_announcements_scailo_proto_rawDescOnce sync.Once
	file_announcements_scailo_proto_rawDescData []byte
)

func file_announcements_scailo_proto_rawDescGZIP() []byte {
	file_announcements_scailo_proto_rawDescOnce.Do(func() {
		file_announcements_scailo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_announcements_scailo_proto_rawDesc), len(file_announcements_scailo_proto_rawDesc)))
	})
	return file_announcements_scailo_proto_rawDescData
}

var file_announcements_scailo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_announcements_scailo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_announcements_scailo_proto_goTypes = []any{
	(ANNOUNCEMENT_SORT_KEY)(0),                     // 0: Scailo.ANNOUNCEMENT_SORT_KEY
	(*AnnouncementsServiceCreateRequest)(nil),      // 1: Scailo.AnnouncementsServiceCreateRequest
	(*AnnouncementsServiceUpdateRequest)(nil),      // 2: Scailo.AnnouncementsServiceUpdateRequest
	(*Announcement)(nil),                           // 3: Scailo.Announcement
	(*AnnouncementsList)(nil),                      // 4: Scailo.AnnouncementsList
	(*AnnouncementsServicePaginationReq)(nil),      // 5: Scailo.AnnouncementsServicePaginationReq
	(*AnnouncementsServicePaginationResponse)(nil), // 6: Scailo.AnnouncementsServicePaginationResponse
	(*AnnouncementsServiceFilterReq)(nil),          // 7: Scailo.AnnouncementsServiceFilterReq
	(*AnnouncementsServiceCountReq)(nil),           // 8: Scailo.AnnouncementsServiceCountReq
	(*AnnouncementsServiceSearchAllReq)(nil),       // 9: Scailo.AnnouncementsServiceSearchAllReq
	(*EmployeeMetadata)(nil),                       // 10: Scailo.EmployeeMetadata
	(*ApprovalMetadata)(nil),                       // 11: Scailo.ApprovalMetadata
	(STANDARD_LIFECYCLE_STATUS)(0),                 // 12: Scailo.STANDARD_LIFECYCLE_STATUS
	(*LogbookLogConciseSLC)(nil),                   // 13: Scailo.LogbookLogConciseSLC
	(BOOL_FILTER)(0),                               // 14: Scailo.BOOL_FILTER
	(SORT_ORDER)(0),                                // 15: Scailo.SORT_ORDER
	(*IdentifierUUIDWithUserComment)(nil),          // 16: Scailo.IdentifierUUIDWithUserComment
	(*Identifier)(nil),                             // 17: Scailo.Identifier
	(*IdentifierUUID)(nil),                         // 18: Scailo.IdentifierUUID
	(*IdentifiersList)(nil),                        // 19: Scailo.IdentifiersList
	(*ActiveStatus)(nil),                           // 20: Scailo.ActiveStatus
	(*CountInSLCStatusRequest)(nil),                // 21: Scailo.CountInSLCStatusRequest
	(*StandardFile)(nil),                           // 22: Scailo.StandardFile
	(*IdentifierResponse)(nil),                     // 23: Scailo.IdentifierResponse
	(*CountResponse)(nil),                          // 24: Scailo.CountResponse
	(*IdentifierUUIDsList)(nil),                    // 25: Scailo.IdentifierUUIDsList
}
var file_announcements_scailo_proto_depIdxs = []int32{
	10, // 0: Scailo.Announcement.metadata:type_name -> Scailo.EmployeeMetadata
	11, // 1: Scailo.Announcement.approval_metadata:type_name -> Scailo.ApprovalMetadata
	12, // 2: Scailo.Announcement.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	13, // 3: Scailo.Announcement.logs:type_name -> Scailo.LogbookLogConciseSLC
	3,  // 4: Scailo.AnnouncementsList.list:type_name -> Scailo.Announcement
	14, // 5: Scailo.AnnouncementsServicePaginationReq.is_active:type_name -> Scailo.BOOL_FILTER
	15, // 6: Scailo.AnnouncementsServicePaginationReq.sort_order:type_name -> Scailo.SORT_ORDER
	0,  // 7: Scailo.AnnouncementsServicePaginationReq.sort_key:type_name -> Scailo.ANNOUNCEMENT_SORT_KEY
	12, // 8: Scailo.AnnouncementsServicePaginationReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	3,  // 9: Scailo.AnnouncementsServicePaginationResponse.payload:type_name -> Scailo.Announcement
	14, // 10: Scailo.AnnouncementsServiceFilterReq.is_active:type_name -> Scailo.BOOL_FILTER
	15, // 11: Scailo.AnnouncementsServiceFilterReq.sort_order:type_name -> Scailo.SORT_ORDER
	0,  // 12: Scailo.AnnouncementsServiceFilterReq.sort_key:type_name -> Scailo.ANNOUNCEMENT_SORT_KEY
	12, // 13: Scailo.AnnouncementsServiceFilterReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	14, // 14: Scailo.AnnouncementsServiceCountReq.is_active:type_name -> Scailo.BOOL_FILTER
	12, // 15: Scailo.AnnouncementsServiceCountReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	14, // 16: Scailo.AnnouncementsServiceSearchAllReq.is_active:type_name -> Scailo.BOOL_FILTER
	15, // 17: Scailo.AnnouncementsServiceSearchAllReq.sort_order:type_name -> Scailo.SORT_ORDER
	0,  // 18: Scailo.AnnouncementsServiceSearchAllReq.sort_key:type_name -> Scailo.ANNOUNCEMENT_SORT_KEY
	12, // 19: Scailo.AnnouncementsServiceSearchAllReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	1,  // 20: Scailo.AnnouncementsService.Create:input_type -> Scailo.AnnouncementsServiceCreateRequest
	1,  // 21: Scailo.AnnouncementsService.Draft:input_type -> Scailo.AnnouncementsServiceCreateRequest
	2,  // 22: Scailo.AnnouncementsService.DraftUpdate:input_type -> Scailo.AnnouncementsServiceUpdateRequest
	16, // 23: Scailo.AnnouncementsService.SendForVerification:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 24: Scailo.AnnouncementsService.Verify:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 25: Scailo.AnnouncementsService.Approve:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 26: Scailo.AnnouncementsService.SendForRevision:input_type -> Scailo.IdentifierUUIDWithUserComment
	2,  // 27: Scailo.AnnouncementsService.RevisionUpdate:input_type -> Scailo.AnnouncementsServiceUpdateRequest
	16, // 28: Scailo.AnnouncementsService.Halt:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 29: Scailo.AnnouncementsService.Discard:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 30: Scailo.AnnouncementsService.Restore:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 31: Scailo.AnnouncementsService.Complete:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 32: Scailo.AnnouncementsService.Repeat:input_type -> Scailo.IdentifierUUIDWithUserComment
	16, // 33: Scailo.AnnouncementsService.CommentAdd:input_type -> Scailo.IdentifierUUIDWithUserComment
	17, // 34: Scailo.AnnouncementsService.ViewByID:input_type -> Scailo.Identifier
	18, // 35: Scailo.AnnouncementsService.ViewByUUID:input_type -> Scailo.IdentifierUUID
	17, // 36: Scailo.AnnouncementsService.ViewEssentialByID:input_type -> Scailo.Identifier
	18, // 37: Scailo.AnnouncementsService.ViewEssentialByUUID:input_type -> Scailo.IdentifierUUID
	19, // 38: Scailo.AnnouncementsService.ViewFromIDs:input_type -> Scailo.IdentifiersList
	20, // 39: Scailo.AnnouncementsService.ViewAll:input_type -> Scailo.ActiveStatus
	18, // 40: Scailo.AnnouncementsService.ViewAllForEntityUUID:input_type -> Scailo.IdentifierUUID
	5,  // 41: Scailo.AnnouncementsService.ViewWithPagination:input_type -> Scailo.AnnouncementsServicePaginationReq
	9,  // 42: Scailo.AnnouncementsService.SearchAll:input_type -> Scailo.AnnouncementsServiceSearchAllReq
	7,  // 43: Scailo.AnnouncementsService.Filter:input_type -> Scailo.AnnouncementsServiceFilterReq
	21, // 44: Scailo.AnnouncementsService.CountInStatus:input_type -> Scailo.CountInSLCStatusRequest
	8,  // 45: Scailo.AnnouncementsService.Count:input_type -> Scailo.AnnouncementsServiceCountReq
	7,  // 46: Scailo.AnnouncementsService.DownloadAsCSV:input_type -> Scailo.AnnouncementsServiceFilterReq
	22, // 47: Scailo.AnnouncementsService.ImportFromCSV:input_type -> Scailo.StandardFile
	23, // 48: Scailo.AnnouncementsService.Create:output_type -> Scailo.IdentifierResponse
	23, // 49: Scailo.AnnouncementsService.Draft:output_type -> Scailo.IdentifierResponse
	23, // 50: Scailo.AnnouncementsService.DraftUpdate:output_type -> Scailo.IdentifierResponse
	23, // 51: Scailo.AnnouncementsService.SendForVerification:output_type -> Scailo.IdentifierResponse
	23, // 52: Scailo.AnnouncementsService.Verify:output_type -> Scailo.IdentifierResponse
	23, // 53: Scailo.AnnouncementsService.Approve:output_type -> Scailo.IdentifierResponse
	23, // 54: Scailo.AnnouncementsService.SendForRevision:output_type -> Scailo.IdentifierResponse
	23, // 55: Scailo.AnnouncementsService.RevisionUpdate:output_type -> Scailo.IdentifierResponse
	23, // 56: Scailo.AnnouncementsService.Halt:output_type -> Scailo.IdentifierResponse
	23, // 57: Scailo.AnnouncementsService.Discard:output_type -> Scailo.IdentifierResponse
	23, // 58: Scailo.AnnouncementsService.Restore:output_type -> Scailo.IdentifierResponse
	23, // 59: Scailo.AnnouncementsService.Complete:output_type -> Scailo.IdentifierResponse
	23, // 60: Scailo.AnnouncementsService.Repeat:output_type -> Scailo.IdentifierResponse
	23, // 61: Scailo.AnnouncementsService.CommentAdd:output_type -> Scailo.IdentifierResponse
	3,  // 62: Scailo.AnnouncementsService.ViewByID:output_type -> Scailo.Announcement
	3,  // 63: Scailo.AnnouncementsService.ViewByUUID:output_type -> Scailo.Announcement
	3,  // 64: Scailo.AnnouncementsService.ViewEssentialByID:output_type -> Scailo.Announcement
	3,  // 65: Scailo.AnnouncementsService.ViewEssentialByUUID:output_type -> Scailo.Announcement
	4,  // 66: Scailo.AnnouncementsService.ViewFromIDs:output_type -> Scailo.AnnouncementsList
	4,  // 67: Scailo.AnnouncementsService.ViewAll:output_type -> Scailo.AnnouncementsList
	4,  // 68: Scailo.AnnouncementsService.ViewAllForEntityUUID:output_type -> Scailo.AnnouncementsList
	6,  // 69: Scailo.AnnouncementsService.ViewWithPagination:output_type -> Scailo.AnnouncementsServicePaginationResponse
	4,  // 70: Scailo.AnnouncementsService.SearchAll:output_type -> Scailo.AnnouncementsList
	4,  // 71: Scailo.AnnouncementsService.Filter:output_type -> Scailo.AnnouncementsList
	24, // 72: Scailo.AnnouncementsService.CountInStatus:output_type -> Scailo.CountResponse
	24, // 73: Scailo.AnnouncementsService.Count:output_type -> Scailo.CountResponse
	22, // 74: Scailo.AnnouncementsService.DownloadAsCSV:output_type -> Scailo.StandardFile
	25, // 75: Scailo.AnnouncementsService.ImportFromCSV:output_type -> Scailo.IdentifierUUIDsList
	48, // [48:76] is the sub-list for method output_type
	20, // [20:48] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_announcements_scailo_proto_init() }
func file_announcements_scailo_proto_init() {
	if File_announcements_scailo_proto != nil {
		return
	}
	file_base_scailo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_announcements_scailo_proto_rawDesc), len(file_announcements_scailo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_announcements_scailo_proto_goTypes,
		DependencyIndexes: file_announcements_scailo_proto_depIdxs,
		EnumInfos:         file_announcements_scailo_proto_enumTypes,
		MessageInfos:      file_announcements_scailo_proto_msgTypes,
	}.Build()
	File_announcements_scailo_proto = out.File
	file_announcements_scailo_proto_goTypes = nil
	file_announcements_scailo_proto_depIdxs = nil
}
