// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: visitations.scailo.proto

package sdk

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the available sort keys
type VISITATION_SORT_KEY int32

const (
	// Fetch ordered results by id
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_ID_UNSPECIFIED VISITATION_SORT_KEY = 0
	// Fetch ordered results by the creation timestamp
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_CREATED_AT VISITATION_SORT_KEY = 1
	// Fetch ordered results by the modified timestamp
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_MODIFIED_AT VISITATION_SORT_KEY = 2
	// Fetch ordered results by the approved on timestamp
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_APPROVED_ON VISITATION_SORT_KEY = 3
	// Fetch ordered results by the approved by field
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_APPROVED_BY VISITATION_SORT_KEY = 4
	// Fetch ordered results by the approver's role ID
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_APPROVER_ROLE_ID VISITATION_SORT_KEY = 5
	// Fetch ordered results by the approver's completed on timestamp
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_COMPLETED_ON VISITATION_SORT_KEY = 6
	// Fetch ordered results by the reference ID
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_REFERENCE_ID VISITATION_SORT_KEY = 10
	// Fetch ordered results by the final ref number
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_FINAL_REF_NUMBER VISITATION_SORT_KEY = 11
	// Fetch ordered results by the user ID
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_USER_ID VISITATION_SORT_KEY = 12
	// Fetch ordered results by the associate ID
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_ASSOCIATE_ID VISITATION_SORT_KEY = 13
	// Fetch ordered results by the "from timestamp"
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_ENTRY_TIMESTAMP VISITATION_SORT_KEY = 14
	// Fetch ordered results by the "to timestamp"
	VISITATION_SORT_KEY_VISITATION_SORT_KEY_EXIT_TIMESTAMP VISITATION_SORT_KEY = 15
)

// Enum value maps for VISITATION_SORT_KEY.
var (
	VISITATION_SORT_KEY_name = map[int32]string{
		0:  "VISITATION_SORT_KEY_ID_UNSPECIFIED",
		1:  "VISITATION_SORT_KEY_CREATED_AT",
		2:  "VISITATION_SORT_KEY_MODIFIED_AT",
		3:  "VISITATION_SORT_KEY_APPROVED_ON",
		4:  "VISITATION_SORT_KEY_APPROVED_BY",
		5:  "VISITATION_SORT_KEY_APPROVER_ROLE_ID",
		6:  "VISITATION_SORT_KEY_COMPLETED_ON",
		10: "VISITATION_SORT_KEY_REFERENCE_ID",
		11: "VISITATION_SORT_KEY_FINAL_REF_NUMBER",
		12: "VISITATION_SORT_KEY_USER_ID",
		13: "VISITATION_SORT_KEY_ASSOCIATE_ID",
		14: "VISITATION_SORT_KEY_ENTRY_TIMESTAMP",
		15: "VISITATION_SORT_KEY_EXIT_TIMESTAMP",
	}
	VISITATION_SORT_KEY_value = map[string]int32{
		"VISITATION_SORT_KEY_ID_UNSPECIFIED":   0,
		"VISITATION_SORT_KEY_CREATED_AT":       1,
		"VISITATION_SORT_KEY_MODIFIED_AT":      2,
		"VISITATION_SORT_KEY_APPROVED_ON":      3,
		"VISITATION_SORT_KEY_APPROVED_BY":      4,
		"VISITATION_SORT_KEY_APPROVER_ROLE_ID": 5,
		"VISITATION_SORT_KEY_COMPLETED_ON":     6,
		"VISITATION_SORT_KEY_REFERENCE_ID":     10,
		"VISITATION_SORT_KEY_FINAL_REF_NUMBER": 11,
		"VISITATION_SORT_KEY_USER_ID":          12,
		"VISITATION_SORT_KEY_ASSOCIATE_ID":     13,
		"VISITATION_SORT_KEY_ENTRY_TIMESTAMP":  14,
		"VISITATION_SORT_KEY_EXIT_TIMESTAMP":   15,
	}
)

func (x VISITATION_SORT_KEY) Enum() *VISITATION_SORT_KEY {
	p := new(VISITATION_SORT_KEY)
	*p = x
	return p
}

func (x VISITATION_SORT_KEY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VISITATION_SORT_KEY) Descriptor() protoreflect.EnumDescriptor {
	return file_visitations_scailo_proto_enumTypes[0].Descriptor()
}

func (VISITATION_SORT_KEY) Type() protoreflect.EnumType {
	return &file_visitations_scailo_proto_enumTypes[0]
}

func (x VISITATION_SORT_KEY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VISITATION_SORT_KEY.Descriptor instead.
func (VISITATION_SORT_KEY) EnumDescriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{0}
}

// Describes the parameters necessary to create a record
type VisitationsServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores a globally unique entity UUID. This will be set at the organization level
	EntityUuid string `protobuf:"bytes,1,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// Stores any comment that the user might add during this operation
	UserComment string `protobuf:"bytes,2,opt,name=user_comment,json=userComment,proto3" json:"user_comment,omitempty"`
	// The associated vault folder ID
	VaultFolderId uint64 `protobuf:"varint,9,opt,name=vault_folder_id,json=vaultFolderId,proto3" json:"vault_folder_id,omitempty"`
	// The reference ID of the visitation
	ReferenceId string `protobuf:"bytes,10,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	// The ID of the user who is being visited
	UserId uint64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the associate who has requested for visitation
	AssociateId uint64 `protobuf:"varint,12,opt,name=associate_id,json=associateId,proto3" json:"associate_id,omitempty"`
	// The UNIX timestamp from when the visitation begins
	EntryTimestamp uint64 `protobuf:"varint,13,opt,name=entry_timestamp,json=entryTimestamp,proto3" json:"entry_timestamp,omitempty"`
	// The UNIX timestamp from when the visitation ends
	ExitTimestamp uint64 `protobuf:"varint,14,opt,name=exit_timestamp,json=exitTimestamp,proto3" json:"exit_timestamp,omitempty"`
	// The description of the visitation
	Description string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	// The list of dynamic forms
	FormData      []*FormFieldDatumCreateRequest `protobuf:"bytes,30,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServiceCreateRequest) Reset() {
	*x = VisitationsServiceCreateRequest{}
	mi := &file_visitations_scailo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceCreateRequest) ProtoMessage() {}

func (x *VisitationsServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*VisitationsServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{0}
}

func (x *VisitationsServiceCreateRequest) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *VisitationsServiceCreateRequest) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *VisitationsServiceCreateRequest) GetVaultFolderId() uint64 {
	if x != nil {
		return x.VaultFolderId
	}
	return 0
}

func (x *VisitationsServiceCreateRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *VisitationsServiceCreateRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VisitationsServiceCreateRequest) GetAssociateId() uint64 {
	if x != nil {
		return x.AssociateId
	}
	return 0
}

func (x *VisitationsServiceCreateRequest) GetEntryTimestamp() uint64 {
	if x != nil {
		return x.EntryTimestamp
	}
	return 0
}

func (x *VisitationsServiceCreateRequest) GetExitTimestamp() uint64 {
	if x != nil {
		return x.ExitTimestamp
	}
	return 0
}

func (x *VisitationsServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VisitationsServiceCreateRequest) GetFormData() []*FormFieldDatumCreateRequest {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Describes the parameters necessary to update a record
type VisitationsServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores any comment that the user might add during this operation
	UserComment string `protobuf:"bytes,1,opt,name=user_comment,json=userComment,proto3" json:"user_comment,omitempty"`
	// The ID of the record that needs to be updated
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Optional boolean value that stores if a notification needs to be sent to users about the update to the record. This is useful when a subsequent operation needs to be performed immediately (such as send to verification after updating the revision)
	NotifyUsers bool `protobuf:"varint,3,opt,name=notify_users,json=notifyUsers,proto3" json:"notify_users,omitempty"`
	// The associated vault folder ID
	VaultFolderId uint64 `protobuf:"varint,9,opt,name=vault_folder_id,json=vaultFolderId,proto3" json:"vault_folder_id,omitempty"`
	// The reference ID of the visitation
	ReferenceId string `protobuf:"bytes,10,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	// The UNIX timestamp from when the visitation begins
	EntryTimestamp uint64 `protobuf:"varint,12,opt,name=entry_timestamp,json=entryTimestamp,proto3" json:"entry_timestamp,omitempty"`
	// The UNIX timestamp from when the visitation ends
	ExitTimestamp uint64 `protobuf:"varint,13,opt,name=exit_timestamp,json=exitTimestamp,proto3" json:"exit_timestamp,omitempty"`
	// The description of the visitation
	Description string `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	// The list of dynamic forms
	FormData      []*FormFieldDatumCreateRequest `protobuf:"bytes,30,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServiceUpdateRequest) Reset() {
	*x = VisitationsServiceUpdateRequest{}
	mi := &file_visitations_scailo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceUpdateRequest) ProtoMessage() {}

func (x *VisitationsServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*VisitationsServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{1}
}

func (x *VisitationsServiceUpdateRequest) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *VisitationsServiceUpdateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VisitationsServiceUpdateRequest) GetNotifyUsers() bool {
	if x != nil {
		return x.NotifyUsers
	}
	return false
}

func (x *VisitationsServiceUpdateRequest) GetVaultFolderId() uint64 {
	if x != nil {
		return x.VaultFolderId
	}
	return 0
}

func (x *VisitationsServiceUpdateRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *VisitationsServiceUpdateRequest) GetEntryTimestamp() uint64 {
	if x != nil {
		return x.EntryTimestamp
	}
	return 0
}

func (x *VisitationsServiceUpdateRequest) GetExitTimestamp() uint64 {
	if x != nil {
		return x.ExitTimestamp
	}
	return 0
}

func (x *VisitationsServiceUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VisitationsServiceUpdateRequest) GetFormData() []*FormFieldDatumCreateRequest {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Describes the message payload that is necessary to create an entry record. This will most likely be called only from mobile devices.
type VisitationsServiceImageEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores a globally unique entity UUID. This will be set at the organization level
	EntityUuid string `protobuf:"bytes,1,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// // The reference ID of the visitation
	//
	//	string reference_id = 10 [(buf.validate.field).string = {
	//	    pattern: "[0-9A-Za-z ]+$", // Allow spaces
	//	}];
	//
	// The ID of the user who is being visited
	UserId uint64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the associate who has requested for visitation
	AssociateId uint64 `protobuf:"varint,12,opt,name=associate_id,json=associateId,proto3" json:"associate_id,omitempty"`
	// The raw image content of the entry image
	EntryImage []byte `protobuf:"bytes,13,opt,name=entry_image,json=entryImage,proto3" json:"entry_image,omitempty"`
	// The MIME type of the entry image
	EntryImageMimeType string `protobuf:"bytes,14,opt,name=entry_image_mime_type,json=entryImageMimeType,proto3" json:"entry_image_mime_type,omitempty"`
	// The description of the visitation
	Description string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	// The latitude of where the entry was recorded
	EntryLatitude float64 `protobuf:"fixed64,16,opt,name=entry_latitude,json=entryLatitude,proto3" json:"entry_latitude,omitempty"`
	// The longiture of where the entry was recorded
	EntryLongitude float64 `protobuf:"fixed64,17,opt,name=entry_longitude,json=entryLongitude,proto3" json:"entry_longitude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VisitationsServiceImageEntryRequest) Reset() {
	*x = VisitationsServiceImageEntryRequest{}
	mi := &file_visitations_scailo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceImageEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceImageEntryRequest) ProtoMessage() {}

func (x *VisitationsServiceImageEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceImageEntryRequest.ProtoReflect.Descriptor instead.
func (*VisitationsServiceImageEntryRequest) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{2}
}

func (x *VisitationsServiceImageEntryRequest) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *VisitationsServiceImageEntryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VisitationsServiceImageEntryRequest) GetAssociateId() uint64 {
	if x != nil {
		return x.AssociateId
	}
	return 0
}

func (x *VisitationsServiceImageEntryRequest) GetEntryImage() []byte {
	if x != nil {
		return x.EntryImage
	}
	return nil
}

func (x *VisitationsServiceImageEntryRequest) GetEntryImageMimeType() string {
	if x != nil {
		return x.EntryImageMimeType
	}
	return ""
}

func (x *VisitationsServiceImageEntryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VisitationsServiceImageEntryRequest) GetEntryLatitude() float64 {
	if x != nil {
		return x.EntryLatitude
	}
	return 0
}

func (x *VisitationsServiceImageEntryRequest) GetEntryLongitude() float64 {
	if x != nil {
		return x.EntryLongitude
	}
	return 0
}

// Describes the message payload that is necessary to create an exit record. This will most likely be called only from mobile devices.
type VisitationsServiceImageExitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the record that needs to be updated
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// The raw image content of the exit image
	ExitImage []byte `protobuf:"bytes,13,opt,name=exit_image,json=exitImage,proto3" json:"exit_image,omitempty"`
	// The MIME type of the exit image
	ExitImageMimeType string `protobuf:"bytes,14,opt,name=exit_image_mime_type,json=exitImageMimeType,proto3" json:"exit_image_mime_type,omitempty"`
	// The latitude of where the exit was recorded
	ExitLatitude float64 `protobuf:"fixed64,15,opt,name=exit_latitude,json=exitLatitude,proto3" json:"exit_latitude,omitempty"`
	// The longiture of where the exit was recorded
	ExitLongitude float64 `protobuf:"fixed64,16,opt,name=exit_longitude,json=exitLongitude,proto3" json:"exit_longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServiceImageExitRequest) Reset() {
	*x = VisitationsServiceImageExitRequest{}
	mi := &file_visitations_scailo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceImageExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceImageExitRequest) ProtoMessage() {}

func (x *VisitationsServiceImageExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceImageExitRequest.ProtoReflect.Descriptor instead.
func (*VisitationsServiceImageExitRequest) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{3}
}

func (x *VisitationsServiceImageExitRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VisitationsServiceImageExitRequest) GetExitImage() []byte {
	if x != nil {
		return x.ExitImage
	}
	return nil
}

func (x *VisitationsServiceImageExitRequest) GetExitImageMimeType() string {
	if x != nil {
		return x.ExitImageMimeType
	}
	return ""
}

func (x *VisitationsServiceImageExitRequest) GetExitLatitude() float64 {
	if x != nil {
		return x.ExitLatitude
	}
	return 0
}

func (x *VisitationsServiceImageExitRequest) GetExitLongitude() float64 {
	if x != nil {
		return x.ExitLongitude
	}
	return 0
}

// Describes the parameters that are part of a standard response
type Visitation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stores a globally unique entity UUID. This will be set at the organization level
	EntityUuid string `protobuf:"bytes,1,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// Stores the metadata of this visitation
	Metadata *EmployeeMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Stores the approval metadata
	ApprovalMetadata *ApprovalMetadata `protobuf:"bytes,3,opt,name=approval_metadata,json=approvalMetadata,proto3" json:"approval_metadata,omitempty"`
	// The status of this visitation
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,4,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// Stores the logs of every operation performed on this visitation
	Logs []*LogbookLogConciseSLC `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	// The timestamp of when this visitation was marked as completed
	CompletedOn uint64 `protobuf:"varint,6,opt,name=completed_on,json=completedOn,proto3" json:"completed_on,omitempty"`
	// The associated vault folder ID
	VaultFolderId uint64 `protobuf:"varint,9,opt,name=vault_folder_id,json=vaultFolderId,proto3" json:"vault_folder_id,omitempty"`
	// The reference_id of the visitation
	ReferenceId string `protobuf:"bytes,10,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	// The unique reference number that has been automatically generated
	FinalRefNumber string `protobuf:"bytes,11,opt,name=final_ref_number,json=finalRefNumber,proto3" json:"final_ref_number,omitempty"`
	// The ID of the user who is being visited
	UserId uint64 `protobuf:"varint,12,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the associate who has requested for visitation
	AssociateId uint64 `protobuf:"varint,13,opt,name=associate_id,json=associateId,proto3" json:"associate_id,omitempty"`
	// The UNIX timestamp from when the visitation begins
	EntryTimestamp uint64 `protobuf:"varint,14,opt,name=entry_timestamp,json=entryTimestamp,proto3" json:"entry_timestamp,omitempty"`
	// The UNIX timestamp from when the visitation ends
	ExitTimestamp uint64 `protobuf:"varint,15,opt,name=exit_timestamp,json=exitTimestamp,proto3" json:"exit_timestamp,omitempty"`
	// The description of the visitation
	Description string `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	// The list of dynamic forms
	FormData      []*FormFieldDatum `protobuf:"bytes,30,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Visitation) Reset() {
	*x = Visitation{}
	mi := &file_visitations_scailo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Visitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visitation) ProtoMessage() {}

func (x *Visitation) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visitation.ProtoReflect.Descriptor instead.
func (*Visitation) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{4}
}

func (x *Visitation) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *Visitation) GetMetadata() *EmployeeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Visitation) GetApprovalMetadata() *ApprovalMetadata {
	if x != nil {
		return x.ApprovalMetadata
	}
	return nil
}

func (x *Visitation) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *Visitation) GetLogs() []*LogbookLogConciseSLC {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Visitation) GetCompletedOn() uint64 {
	if x != nil {
		return x.CompletedOn
	}
	return 0
}

func (x *Visitation) GetVaultFolderId() uint64 {
	if x != nil {
		return x.VaultFolderId
	}
	return 0
}

func (x *Visitation) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Visitation) GetFinalRefNumber() string {
	if x != nil {
		return x.FinalRefNumber
	}
	return ""
}

func (x *Visitation) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Visitation) GetAssociateId() uint64 {
	if x != nil {
		return x.AssociateId
	}
	return 0
}

func (x *Visitation) GetEntryTimestamp() uint64 {
	if x != nil {
		return x.EntryTimestamp
	}
	return 0
}

func (x *Visitation) GetExitTimestamp() uint64 {
	if x != nil {
		return x.ExitTimestamp
	}
	return 0
}

func (x *Visitation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Visitation) GetFormData() []*FormFieldDatum {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Describes the message consisting of the list of records
type VisitationsList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of records
	List          []*Visitation `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsList) Reset() {
	*x = VisitationsList{}
	mi := &file_visitations_scailo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsList) ProtoMessage() {}

func (x *VisitationsList) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsList.ProtoReflect.Descriptor instead.
func (*VisitationsList) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{5}
}

func (x *VisitationsList) GetList() []*Visitation {
	if x != nil {
		return x.List
	}
	return nil
}

// Describes a pagination request to retrieve records
type VisitationsServicePaginationReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The number of records that need to be sent in the response
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// The number that need to be offset by before fetching the records
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The sort order that is to be used to fetch the pagination response
	SortOrder SORT_ORDER `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=Scailo.SORT_ORDER" json:"sort_order,omitempty"`
	// The sort key that is to be used to fetch the pagination response
	SortKey VISITATION_SORT_KEY `protobuf:"varint,5,opt,name=sort_key,json=sortKey,proto3,enum=Scailo.VISITATION_SORT_KEY" json:"sort_key,omitempty"`
	// The status of this visitation
	Status        STANDARD_LIFECYCLE_STATUS `protobuf:"varint,6,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServicePaginationReq) Reset() {
	*x = VisitationsServicePaginationReq{}
	mi := &file_visitations_scailo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServicePaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServicePaginationReq) ProtoMessage() {}

func (x *VisitationsServicePaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServicePaginationReq.ProtoReflect.Descriptor instead.
func (*VisitationsServicePaginationReq) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{6}
}

func (x *VisitationsServicePaginationReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *VisitationsServicePaginationReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VisitationsServicePaginationReq) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VisitationsServicePaginationReq) GetSortOrder() SORT_ORDER {
	if x != nil {
		return x.SortOrder
	}
	return SORT_ORDER_ASCENDING_UNSPECIFIED
}

func (x *VisitationsServicePaginationReq) GetSortKey() VISITATION_SORT_KEY {
	if x != nil {
		return x.SortKey
	}
	return VISITATION_SORT_KEY_VISITATION_SORT_KEY_ID_UNSPECIFIED
}

func (x *VisitationsServicePaginationReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

// Describes the response to a pagination request
type VisitationsServicePaginationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of records in this payload
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// The number that has been offset before fetching the records. This is the same value that has been sent as part of the pagination request
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The total number of records that are available
	Total uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// The list of records
	Payload       []*Visitation `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServicePaginationResponse) Reset() {
	*x = VisitationsServicePaginationResponse{}
	mi := &file_visitations_scailo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServicePaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServicePaginationResponse) ProtoMessage() {}

func (x *VisitationsServicePaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServicePaginationResponse.ProtoReflect.Descriptor instead.
func (*VisitationsServicePaginationResponse) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{7}
}

func (x *VisitationsServicePaginationResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VisitationsServicePaginationResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VisitationsServicePaginationResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *VisitationsServicePaginationResponse) GetPayload() []*Visitation {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Describes the base request payload of a filter search
type VisitationsServiceFilterReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The number of records that need to be sent in the response. Returns all records if it is set to -1
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// The number that need to be offset by before fetching the records
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The sort order that is to be used to fetch the pagination response
	SortOrder SORT_ORDER `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=Scailo.SORT_ORDER" json:"sort_order,omitempty"`
	// The sort key that is to be used to fetch the pagination response
	SortKey VISITATION_SORT_KEY `protobuf:"varint,5,opt,name=sort_key,json=sortKey,proto3,enum=Scailo.VISITATION_SORT_KEY" json:"sort_key,omitempty"`
	// The minimum timestamp that needs to be considered to filter by creation
	CreationTimestampStart uint64 `protobuf:"varint,101,opt,name=creation_timestamp_start,json=creationTimestampStart,proto3" json:"creation_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by creation
	CreationTimestampEnd uint64 `protobuf:"varint,102,opt,name=creation_timestamp_end,json=creationTimestampEnd,proto3" json:"creation_timestamp_end,omitempty"`
	// The minimum timestamp that needs to be considered to filter by modification
	ModificationTimestampStart uint64 `protobuf:"varint,103,opt,name=modification_timestamp_start,json=modificationTimestampStart,proto3" json:"modification_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by modification
	ModificationTimestampEnd uint64 `protobuf:"varint,104,opt,name=modification_timestamp_end,json=modificationTimestampEnd,proto3" json:"modification_timestamp_end,omitempty"`
	// The entity UUID that is to be used to filter records
	EntityUuid string `protobuf:"bytes,8,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// The status of this visitation
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,10,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// The start range of approved timestamp
	ApprovedOnStart uint64 `protobuf:"varint,11,opt,name=approved_on_start,json=approvedOnStart,proto3" json:"approved_on_start,omitempty"`
	// The end range of approved timestamp
	ApprovedOnEnd uint64 `protobuf:"varint,12,opt,name=approved_on_end,json=approvedOnEnd,proto3" json:"approved_on_end,omitempty"`
	// The ID of the approver
	ApprovedByUserId uint64 `protobuf:"varint,13,opt,name=approved_by_user_id,json=approvedByUserId,proto3" json:"approved_by_user_id,omitempty"`
	// The role ID of the approver
	ApproverRoleId uint64 `protobuf:"varint,14,opt,name=approver_role_id,json=approverRoleId,proto3" json:"approver_role_id,omitempty"`
	// The start range of completed timestamp
	CompletedOnStart uint64 `protobuf:"varint,15,opt,name=completed_on_start,json=completedOnStart,proto3" json:"completed_on_start,omitempty"`
	// The end range of completed timestamp
	CompletedOnEnd uint64 `protobuf:"varint,16,opt,name=completed_on_end,json=completedOnEnd,proto3" json:"completed_on_end,omitempty"`
	// The reference_id of the visitation
	ReferenceId string `protobuf:"bytes,20,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	// The unique reference number that has been automatically generated
	FinalRefNumber string `protobuf:"bytes,21,opt,name=final_ref_number,json=finalRefNumber,proto3" json:"final_ref_number,omitempty"`
	// The ID of the user who is being visited
	UserId uint64 `protobuf:"varint,22,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the associate who has requested for visitation
	AssociateId uint64 `protobuf:"varint,23,opt,name=associate_id,json=associateId,proto3" json:"associate_id,omitempty"`
	// The start range of "from timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	EntryTimestampStart uint64 `protobuf:"varint,24,opt,name=entry_timestamp_start,json=entryTimestampStart,proto3" json:"entry_timestamp_start,omitempty"`
	// The end range of "from timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	EntryTimestampEnd uint64 `protobuf:"varint,25,opt,name=entry_timestamp_end,json=entryTimestampEnd,proto3" json:"entry_timestamp_end,omitempty"`
	// The start range of "to timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	ExitTimestampStart uint64 `protobuf:"varint,26,opt,name=exit_timestamp_start,json=exitTimestampStart,proto3" json:"exit_timestamp_start,omitempty"`
	// The end range of "to timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	ExitTimestampEnd uint64 `protobuf:"varint,27,opt,name=exit_timestamp_end,json=exitTimestampEnd,proto3" json:"exit_timestamp_end,omitempty"`
	// The list of form data filters
	FormData      []*FormFieldDatumFilterRequest `protobuf:"bytes,500,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServiceFilterReq) Reset() {
	*x = VisitationsServiceFilterReq{}
	mi := &file_visitations_scailo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceFilterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceFilterReq) ProtoMessage() {}

func (x *VisitationsServiceFilterReq) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceFilterReq.ProtoReflect.Descriptor instead.
func (*VisitationsServiceFilterReq) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{8}
}

func (x *VisitationsServiceFilterReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *VisitationsServiceFilterReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetSortOrder() SORT_ORDER {
	if x != nil {
		return x.SortOrder
	}
	return SORT_ORDER_ASCENDING_UNSPECIFIED
}

func (x *VisitationsServiceFilterReq) GetSortKey() VISITATION_SORT_KEY {
	if x != nil {
		return x.SortKey
	}
	return VISITATION_SORT_KEY_VISITATION_SORT_KEY_ID_UNSPECIFIED
}

func (x *VisitationsServiceFilterReq) GetCreationTimestampStart() uint64 {
	if x != nil {
		return x.CreationTimestampStart
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetCreationTimestampEnd() uint64 {
	if x != nil {
		return x.CreationTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetModificationTimestampStart() uint64 {
	if x != nil {
		return x.ModificationTimestampStart
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetModificationTimestampEnd() uint64 {
	if x != nil {
		return x.ModificationTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *VisitationsServiceFilterReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *VisitationsServiceFilterReq) GetApprovedOnStart() uint64 {
	if x != nil {
		return x.ApprovedOnStart
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetApprovedOnEnd() uint64 {
	if x != nil {
		return x.ApprovedOnEnd
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetApprovedByUserId() uint64 {
	if x != nil {
		return x.ApprovedByUserId
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetApproverRoleId() uint64 {
	if x != nil {
		return x.ApproverRoleId
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetCompletedOnStart() uint64 {
	if x != nil {
		return x.CompletedOnStart
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetCompletedOnEnd() uint64 {
	if x != nil {
		return x.CompletedOnEnd
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *VisitationsServiceFilterReq) GetFinalRefNumber() string {
	if x != nil {
		return x.FinalRefNumber
	}
	return ""
}

func (x *VisitationsServiceFilterReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetAssociateId() uint64 {
	if x != nil {
		return x.AssociateId
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetEntryTimestampStart() uint64 {
	if x != nil {
		return x.EntryTimestampStart
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetEntryTimestampEnd() uint64 {
	if x != nil {
		return x.EntryTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetExitTimestampStart() uint64 {
	if x != nil {
		return x.ExitTimestampStart
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetExitTimestampEnd() uint64 {
	if x != nil {
		return x.ExitTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceFilterReq) GetFormData() []*FormFieldDatumFilterRequest {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Describes the base request payload of a count search
type VisitationsServiceCountReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The minimum timestamp that needs to be considered to filter by creation
	CreationTimestampStart uint64 `protobuf:"varint,101,opt,name=creation_timestamp_start,json=creationTimestampStart,proto3" json:"creation_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by creation
	CreationTimestampEnd uint64 `protobuf:"varint,102,opt,name=creation_timestamp_end,json=creationTimestampEnd,proto3" json:"creation_timestamp_end,omitempty"`
	// The minimum timestamp that needs to be considered to filter by modification
	ModificationTimestampStart uint64 `protobuf:"varint,103,opt,name=modification_timestamp_start,json=modificationTimestampStart,proto3" json:"modification_timestamp_start,omitempty"`
	// The maximum timestamp that needs to be considered to filter by modification
	ModificationTimestampEnd uint64 `protobuf:"varint,104,opt,name=modification_timestamp_end,json=modificationTimestampEnd,proto3" json:"modification_timestamp_end,omitempty"`
	// The entity UUID that is to be used to filter records
	EntityUuid string `protobuf:"bytes,8,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// The status of this visitation
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,10,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// The start range of approved timestamp
	ApprovedOnStart uint64 `protobuf:"varint,11,opt,name=approved_on_start,json=approvedOnStart,proto3" json:"approved_on_start,omitempty"`
	// The end range of approved timestamp
	ApprovedOnEnd uint64 `protobuf:"varint,12,opt,name=approved_on_end,json=approvedOnEnd,proto3" json:"approved_on_end,omitempty"`
	// The ID of the approver
	ApprovedByUserId uint64 `protobuf:"varint,13,opt,name=approved_by_user_id,json=approvedByUserId,proto3" json:"approved_by_user_id,omitempty"`
	// The role ID of the approver
	ApproverRoleId uint64 `protobuf:"varint,14,opt,name=approver_role_id,json=approverRoleId,proto3" json:"approver_role_id,omitempty"`
	// The start range of completed timestamp
	CompletedOnStart uint64 `protobuf:"varint,15,opt,name=completed_on_start,json=completedOnStart,proto3" json:"completed_on_start,omitempty"`
	// The end range of completed timestamp
	CompletedOnEnd uint64 `protobuf:"varint,16,opt,name=completed_on_end,json=completedOnEnd,proto3" json:"completed_on_end,omitempty"`
	// The reference_id of the visitation
	ReferenceId string `protobuf:"bytes,20,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	// The unique reference number that has been automatically generated
	FinalRefNumber string `protobuf:"bytes,21,opt,name=final_ref_number,json=finalRefNumber,proto3" json:"final_ref_number,omitempty"`
	// The ID of the user who is being visited
	UserId uint64 `protobuf:"varint,22,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the associate who has requested for visitation
	AssociateId uint64 `protobuf:"varint,23,opt,name=associate_id,json=associateId,proto3" json:"associate_id,omitempty"`
	// The start range of "from timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	EntryTimestampStart uint64 `protobuf:"varint,24,opt,name=entry_timestamp_start,json=entryTimestampStart,proto3" json:"entry_timestamp_start,omitempty"`
	// The end range of "from timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	EntryTimestampEnd uint64 `protobuf:"varint,25,opt,name=entry_timestamp_end,json=entryTimestampEnd,proto3" json:"entry_timestamp_end,omitempty"`
	// The start range of "to timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	ExitTimestampStart uint64 `protobuf:"varint,26,opt,name=exit_timestamp_start,json=exitTimestampStart,proto3" json:"exit_timestamp_start,omitempty"`
	// The end range of "to timestamp". 0 value will be considered. To prevent this from taken into consideration, set it to -1,
	ExitTimestampEnd uint64 `protobuf:"varint,27,opt,name=exit_timestamp_end,json=exitTimestampEnd,proto3" json:"exit_timestamp_end,omitempty"`
	// The list of form data filters
	FormData      []*FormFieldDatumFilterRequest `protobuf:"bytes,500,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServiceCountReq) Reset() {
	*x = VisitationsServiceCountReq{}
	mi := &file_visitations_scailo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceCountReq) ProtoMessage() {}

func (x *VisitationsServiceCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceCountReq.ProtoReflect.Descriptor instead.
func (*VisitationsServiceCountReq) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{9}
}

func (x *VisitationsServiceCountReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *VisitationsServiceCountReq) GetCreationTimestampStart() uint64 {
	if x != nil {
		return x.CreationTimestampStart
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetCreationTimestampEnd() uint64 {
	if x != nil {
		return x.CreationTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetModificationTimestampStart() uint64 {
	if x != nil {
		return x.ModificationTimestampStart
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetModificationTimestampEnd() uint64 {
	if x != nil {
		return x.ModificationTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *VisitationsServiceCountReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *VisitationsServiceCountReq) GetApprovedOnStart() uint64 {
	if x != nil {
		return x.ApprovedOnStart
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetApprovedOnEnd() uint64 {
	if x != nil {
		return x.ApprovedOnEnd
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetApprovedByUserId() uint64 {
	if x != nil {
		return x.ApprovedByUserId
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetApproverRoleId() uint64 {
	if x != nil {
		return x.ApproverRoleId
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetCompletedOnStart() uint64 {
	if x != nil {
		return x.CompletedOnStart
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetCompletedOnEnd() uint64 {
	if x != nil {
		return x.CompletedOnEnd
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *VisitationsServiceCountReq) GetFinalRefNumber() string {
	if x != nil {
		return x.FinalRefNumber
	}
	return ""
}

func (x *VisitationsServiceCountReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetAssociateId() uint64 {
	if x != nil {
		return x.AssociateId
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetEntryTimestampStart() uint64 {
	if x != nil {
		return x.EntryTimestampStart
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetEntryTimestampEnd() uint64 {
	if x != nil {
		return x.EntryTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetExitTimestampStart() uint64 {
	if x != nil {
		return x.ExitTimestampStart
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetExitTimestampEnd() uint64 {
	if x != nil {
		return x.ExitTimestampEnd
	}
	return 0
}

func (x *VisitationsServiceCountReq) GetFormData() []*FormFieldDatumFilterRequest {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Describes the request payload for performing a generic search operation on records
type VisitationsServiceSearchAllReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, then returns only active records. If false, then returns only inactive records
	IsActive BOOL_FILTER `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,enum=Scailo.BOOL_FILTER" json:"is_active,omitempty"`
	// The number of records that need to be sent in the response. Returns all records if it is set to -1
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// The number that need to be offset by before fetching the records
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The sort order that is to be used to fetch the pagination response
	SortOrder SORT_ORDER `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=Scailo.SORT_ORDER" json:"sort_order,omitempty"`
	// The sort key that is to be used to fetch the pagination response
	SortKey VISITATION_SORT_KEY `protobuf:"varint,5,opt,name=sort_key,json=sortKey,proto3,enum=Scailo.VISITATION_SORT_KEY" json:"sort_key,omitempty"`
	// The entity UUID that is to be used to filter records
	EntityUuid string `protobuf:"bytes,6,opt,name=entity_uuid,json=entityUuid,proto3" json:"entity_uuid,omitempty"`
	// Limit the search space to the given status
	Status STANDARD_LIFECYCLE_STATUS `protobuf:"varint,10,opt,name=status,proto3,enum=Scailo.STANDARD_LIFECYCLE_STATUS" json:"status,omitempty"`
	// Describes the key with which the search operation needs to be performed
	SearchKey string `protobuf:"bytes,11,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	// The ID of the user who is being visited
	UserId        uint64 `protobuf:"varint,22,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitationsServiceSearchAllReq) Reset() {
	*x = VisitationsServiceSearchAllReq{}
	mi := &file_visitations_scailo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitationsServiceSearchAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitationsServiceSearchAllReq) ProtoMessage() {}

func (x *VisitationsServiceSearchAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_visitations_scailo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitationsServiceSearchAllReq.ProtoReflect.Descriptor instead.
func (*VisitationsServiceSearchAllReq) Descriptor() ([]byte, []int) {
	return file_visitations_scailo_proto_rawDescGZIP(), []int{10}
}

func (x *VisitationsServiceSearchAllReq) GetIsActive() BOOL_FILTER {
	if x != nil {
		return x.IsActive
	}
	return BOOL_FILTER_BOOL_FILTER_ANY_UNSPECIFIED
}

func (x *VisitationsServiceSearchAllReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VisitationsServiceSearchAllReq) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VisitationsServiceSearchAllReq) GetSortOrder() SORT_ORDER {
	if x != nil {
		return x.SortOrder
	}
	return SORT_ORDER_ASCENDING_UNSPECIFIED
}

func (x *VisitationsServiceSearchAllReq) GetSortKey() VISITATION_SORT_KEY {
	if x != nil {
		return x.SortKey
	}
	return VISITATION_SORT_KEY_VISITATION_SORT_KEY_ID_UNSPECIFIED
}

func (x *VisitationsServiceSearchAllReq) GetEntityUuid() string {
	if x != nil {
		return x.EntityUuid
	}
	return ""
}

func (x *VisitationsServiceSearchAllReq) GetStatus() STANDARD_LIFECYCLE_STATUS {
	if x != nil {
		return x.Status
	}
	return STANDARD_LIFECYCLE_STATUS_ANY_UNSPECIFIED
}

func (x *VisitationsServiceSearchAllReq) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *VisitationsServiceSearchAllReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_visitations_scailo_proto protoreflect.FileDescriptor

const file_visitations_scailo_proto_rawDesc = "" +
	"\n" +
	"\x18visitations.scailo.proto\x12\x06Scailo\x1a\x11base.scailo.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1eforms_fields_data.scailo.proto\x1a\x18magic_links.scailo.proto\"\xfb\x03\n" +
	"\x1fVisitationsServiceCreateRequest\x12\x1f\n" +
	"\ventity_uuid\x18\x01 \x01(\tR\n" +
	"entityUuid\x12!\n" +
	"\fuser_comment\x18\x02 \x01(\tR\vuserComment\x12/\n" +
	"\x0fvault_folder_id\x18\t \x01(\x04B\a\xbaH\x042\x02(\x00R\rvaultFolderId\x128\n" +
	"\freference_id\x18\n" +
	" \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]+$R\vreferenceId\x12 \n" +
	"\auser_id\x18\v \x01(\x04B\a\xbaH\x042\x02 \x00R\x06userId\x12*\n" +
	"\fassociate_id\x18\f \x01(\x04B\a\xbaH\x042\x02 \x00R\vassociateId\x120\n" +
	"\x0fentry_timestamp\x18\r \x01(\x04B\a\xbaH\x042\x02 \x00R\x0eentryTimestamp\x12.\n" +
	"\x0eexit_timestamp\x18\x0e \x01(\x04B\a\xbaH\x042\x02(\x00R\rexitTimestamp\x127\n" +
	"\vdescription\x18\x0f \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]*$R\vdescription\x12@\n" +
	"\tform_data\x18\x1e \x03(\v2#.Scailo.FormFieldDatumCreateRequestR\bformData\"\xc8\x03\n" +
	"\x1fVisitationsServiceUpdateRequest\x12!\n" +
	"\fuser_comment\x18\x01 \x01(\tR\vuserComment\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x02id\x12!\n" +
	"\fnotify_users\x18\x03 \x01(\bR\vnotifyUsers\x12/\n" +
	"\x0fvault_folder_id\x18\t \x01(\x04B\a\xbaH\x042\x02(\x00R\rvaultFolderId\x128\n" +
	"\freference_id\x18\n" +
	" \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]+$R\vreferenceId\x120\n" +
	"\x0fentry_timestamp\x18\f \x01(\x04B\a\xbaH\x042\x02 \x00R\x0eentryTimestamp\x12.\n" +
	"\x0eexit_timestamp\x18\r \x01(\x04B\a\xbaH\x042\x02(\x00R\rexitTimestamp\x127\n" +
	"\vdescription\x18\x0e \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]*$R\vdescription\x12@\n" +
	"\tform_data\x18\x1e \x03(\v2#.Scailo.FormFieldDatumCreateRequestR\bformData\"\xf1\x02\n" +
	"#VisitationsServiceImageEntryRequest\x12\x1f\n" +
	"\ventity_uuid\x18\x01 \x01(\tR\n" +
	"entityUuid\x12 \n" +
	"\auser_id\x18\v \x01(\x04B\a\xbaH\x042\x02 \x00R\x06userId\x12*\n" +
	"\fassociate_id\x18\f \x01(\x04B\a\xbaH\x042\x02 \x00R\vassociateId\x12\x1f\n" +
	"\ventry_image\x18\r \x01(\fR\n" +
	"entryImage\x121\n" +
	"\x15entry_image_mime_type\x18\x0e \x01(\tR\x12entryImageMimeType\x127\n" +
	"\vdescription\x18\x0f \x01(\tB\x15\xbaH\x12r\x102\x0e[0-9A-Za-z ]*$R\vdescription\x12%\n" +
	"\x0eentry_latitude\x18\x10 \x01(\x01R\rentryLatitude\x12'\n" +
	"\x0fentry_longitude\x18\x11 \x01(\x01R\x0eentryLongitude\"\xd9\x01\n" +
	"\"VisitationsServiceImageExitRequest\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x02id\x12\x1d\n" +
	"\n" +
	"exit_image\x18\r \x01(\fR\texitImage\x12/\n" +
	"\x14exit_image_mime_type\x18\x0e \x01(\tR\x11exitImageMimeType\x12#\n" +
	"\rexit_latitude\x18\x0f \x01(\x01R\fexitLatitude\x12%\n" +
	"\x0eexit_longitude\x18\x10 \x01(\x01R\rexitLongitude\"\xa4\x05\n" +
	"\n" +
	"Visitation\x12\x1f\n" +
	"\ventity_uuid\x18\x01 \x01(\tR\n" +
	"entityUuid\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x18.Scailo.EmployeeMetadataR\bmetadata\x12E\n" +
	"\x11approval_metadata\x18\x03 \x01(\v2\x18.Scailo.ApprovalMetadataR\x10approvalMetadata\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x120\n" +
	"\x04logs\x18\x05 \x03(\v2\x1c.Scailo.LogbookLogConciseSLCR\x04logs\x12!\n" +
	"\fcompleted_on\x18\x06 \x01(\x04R\vcompletedOn\x12&\n" +
	"\x0fvault_folder_id\x18\t \x01(\x04R\rvaultFolderId\x12!\n" +
	"\freference_id\x18\n" +
	" \x01(\tR\vreferenceId\x12(\n" +
	"\x10final_ref_number\x18\v \x01(\tR\x0efinalRefNumber\x12 \n" +
	"\auser_id\x18\f \x01(\x04B\a\xbaH\x042\x02 \x00R\x06userId\x12*\n" +
	"\fassociate_id\x18\r \x01(\x04B\a\xbaH\x042\x02 \x00R\vassociateId\x12'\n" +
	"\x0fentry_timestamp\x18\x0e \x01(\x04R\x0eentryTimestamp\x12%\n" +
	"\x0eexit_timestamp\x18\x0f \x01(\x04R\rexitTimestamp\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x123\n" +
	"\tform_data\x18\x1e \x03(\v2\x16.Scailo.FormFieldDatumR\bformData\"9\n" +
	"\x0fVisitationsList\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.Scailo.VisitationR\x04list\"\xb9\x02\n" +
	"\x1fVisitationsServicePaginationReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x12\x1d\n" +
	"\x05count\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x05count\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\x121\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x12.Scailo.SORT_ORDERR\tsortOrder\x126\n" +
	"\bsort_key\x18\x05 \x01(\x0e2\x1b.Scailo.VISITATION_SORT_KEYR\asortKey\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\"\x98\x01\n" +
	"$VisitationsServicePaginationResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12,\n" +
	"\apayload\x18\x04 \x03(\v2\x12.Scailo.VisitationR\apayload\"\xe4\t\n" +
	"\x1bVisitationsServiceFilterReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x12&\n" +
	"\x05count\x18\x02 \x01(\x03B\x10\xbaH\r\"\v(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x05count\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\x121\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x12.Scailo.SORT_ORDERR\tsortOrder\x126\n" +
	"\bsort_key\x18\x05 \x01(\x0e2\x1b.Scailo.VISITATION_SORT_KEYR\asortKey\x128\n" +
	"\x18creation_timestamp_start\x18e \x01(\x04R\x16creationTimestampStart\x124\n" +
	"\x16creation_timestamp_end\x18f \x01(\x04R\x14creationTimestampEnd\x12@\n" +
	"\x1cmodification_timestamp_start\x18g \x01(\x04R\x1amodificationTimestampStart\x12<\n" +
	"\x1amodification_timestamp_end\x18h \x01(\x04R\x18modificationTimestampEnd\x12\x1f\n" +
	"\ventity_uuid\x18\b \x01(\tR\n" +
	"entityUuid\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x12*\n" +
	"\x11approved_on_start\x18\v \x01(\x04R\x0fapprovedOnStart\x12&\n" +
	"\x0fapproved_on_end\x18\f \x01(\x04R\rapprovedOnEnd\x12-\n" +
	"\x13approved_by_user_id\x18\r \x01(\x04R\x10approvedByUserId\x12(\n" +
	"\x10approver_role_id\x18\x0e \x01(\x04R\x0eapproverRoleId\x12,\n" +
	"\x12completed_on_start\x18\x0f \x01(\x04R\x10completedOnStart\x12(\n" +
	"\x10completed_on_end\x18\x10 \x01(\x04R\x0ecompletedOnEnd\x12!\n" +
	"\freference_id\x18\x14 \x01(\tR\vreferenceId\x12(\n" +
	"\x10final_ref_number\x18\x15 \x01(\tR\x0efinalRefNumber\x12\x17\n" +
	"\auser_id\x18\x16 \x01(\x04R\x06userId\x12!\n" +
	"\fassociate_id\x18\x17 \x01(\x04R\vassociateId\x122\n" +
	"\x15entry_timestamp_start\x18\x18 \x01(\x04R\x13entryTimestampStart\x12.\n" +
	"\x13entry_timestamp_end\x18\x19 \x01(\x04R\x11entryTimestampEnd\x120\n" +
	"\x14exit_timestamp_start\x18\x1a \x01(\x04R\x12exitTimestampStart\x12,\n" +
	"\x12exit_timestamp_end\x18\x1b \x01(\x04R\x10exitTimestampEnd\x12A\n" +
	"\tform_data\x18\xf4\x03 \x03(\v2#.Scailo.FormFieldDatumFilterRequestR\bformData\"\xaf\b\n" +
	"\x1aVisitationsServiceCountReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x128\n" +
	"\x18creation_timestamp_start\x18e \x01(\x04R\x16creationTimestampStart\x124\n" +
	"\x16creation_timestamp_end\x18f \x01(\x04R\x14creationTimestampEnd\x12@\n" +
	"\x1cmodification_timestamp_start\x18g \x01(\x04R\x1amodificationTimestampStart\x12<\n" +
	"\x1amodification_timestamp_end\x18h \x01(\x04R\x18modificationTimestampEnd\x12\x1f\n" +
	"\ventity_uuid\x18\b \x01(\tR\n" +
	"entityUuid\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x12*\n" +
	"\x11approved_on_start\x18\v \x01(\x04R\x0fapprovedOnStart\x12&\n" +
	"\x0fapproved_on_end\x18\f \x01(\x04R\rapprovedOnEnd\x12-\n" +
	"\x13approved_by_user_id\x18\r \x01(\x04R\x10approvedByUserId\x12(\n" +
	"\x10approver_role_id\x18\x0e \x01(\x04R\x0eapproverRoleId\x12,\n" +
	"\x12completed_on_start\x18\x0f \x01(\x04R\x10completedOnStart\x12(\n" +
	"\x10completed_on_end\x18\x10 \x01(\x04R\x0ecompletedOnEnd\x12!\n" +
	"\freference_id\x18\x14 \x01(\tR\vreferenceId\x12(\n" +
	"\x10final_ref_number\x18\x15 \x01(\tR\x0efinalRefNumber\x12\x17\n" +
	"\auser_id\x18\x16 \x01(\x04R\x06userId\x12!\n" +
	"\fassociate_id\x18\x17 \x01(\x04R\vassociateId\x122\n" +
	"\x15entry_timestamp_start\x18\x18 \x01(\x04R\x13entryTimestampStart\x12.\n" +
	"\x13entry_timestamp_end\x18\x19 \x01(\x04R\x11entryTimestampEnd\x120\n" +
	"\x14exit_timestamp_start\x18\x1a \x01(\x04R\x12exitTimestampStart\x12,\n" +
	"\x12exit_timestamp_end\x18\x1b \x01(\x04R\x10exitTimestampEnd\x12A\n" +
	"\tform_data\x18\xf4\x03 \x03(\v2#.Scailo.FormFieldDatumFilterRequestR\bformData\"\x9a\x03\n" +
	"\x1eVisitationsServiceSearchAllReq\x120\n" +
	"\tis_active\x18\x01 \x01(\x0e2\x13.Scailo.BOOL_FILTERR\bisActive\x12&\n" +
	"\x05count\x18\x02 \x01(\x03B\x10\xbaH\r\"\v(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x05count\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\x121\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x12.Scailo.SORT_ORDERR\tsortOrder\x126\n" +
	"\bsort_key\x18\x05 \x01(\x0e2\x1b.Scailo.VISITATION_SORT_KEYR\asortKey\x12\x1f\n" +
	"\ventity_uuid\x18\x06 \x01(\tR\n" +
	"entityUuid\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.Scailo.STANDARD_LIFECYCLE_STATUSR\x06status\x12\x1d\n" +
	"\n" +
	"search_key\x18\v \x01(\tR\tsearchKey\x12\x17\n" +
	"\auser_id\x18\x16 \x01(\x04R\x06userId*\x88\x04\n" +
	"\x13VISITATION_SORT_KEY\x12&\n" +
	"\"VISITATION_SORT_KEY_ID_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eVISITATION_SORT_KEY_CREATED_AT\x10\x01\x12#\n" +
	"\x1fVISITATION_SORT_KEY_MODIFIED_AT\x10\x02\x12#\n" +
	"\x1fVISITATION_SORT_KEY_APPROVED_ON\x10\x03\x12#\n" +
	"\x1fVISITATION_SORT_KEY_APPROVED_BY\x10\x04\x12(\n" +
	"$VISITATION_SORT_KEY_APPROVER_ROLE_ID\x10\x05\x12$\n" +
	" VISITATION_SORT_KEY_COMPLETED_ON\x10\x06\x12$\n" +
	" VISITATION_SORT_KEY_REFERENCE_ID\x10\n" +
	"\x12(\n" +
	"$VISITATION_SORT_KEY_FINAL_REF_NUMBER\x10\v\x12\x1f\n" +
	"\x1bVISITATION_SORT_KEY_USER_ID\x10\f\x12$\n" +
	" VISITATION_SORT_KEY_ASSOCIATE_ID\x10\r\x12'\n" +
	"#VISITATION_SORT_KEY_ENTRY_TIMESTAMP\x10\x0e\x12&\n" +
	"\"VISITATION_SORT_KEY_EXIT_TIMESTAMP\x10\x0f2\xad\x17\n" +
	"\x12VisitationsService\x12M\n" +
	"\x06Create\x12'.Scailo.VisitationsServiceCreateRequest\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\x05Draft\x12'.Scailo.VisitationsServiceCreateRequest\x1a\x1a.Scailo.IdentifierResponse\x12R\n" +
	"\vDraftUpdate\x12'.Scailo.VisitationsServiceUpdateRequest\x1a\x1a.Scailo.IdentifierResponse\x12X\n" +
	"\x13SendForVerification\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12K\n" +
	"\x06Verify\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\aApprove\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12T\n" +
	"\x0fSendForRevision\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12U\n" +
	"\x0eRevisionUpdate\x12'.Scailo.VisitationsServiceUpdateRequest\x1a\x1a.Scailo.IdentifierResponse\x12I\n" +
	"\x04Halt\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\aDiscard\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12L\n" +
	"\aRestore\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12M\n" +
	"\bComplete\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12K\n" +
	"\x06Repeat\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12O\n" +
	"\n" +
	"CommentAdd\x12%.Scailo.IdentifierUUIDWithUserComment\x1a\x1a.Scailo.IdentifierResponse\x12_\n" +
	"\x0fCreateMagicLink\x129.Scailo.MagicLinksServiceCreateRequestForSpecificResource\x1a\x11.Scailo.MagicLink\x12[\n" +
	"\x10RecordImageEntry\x12+.Scailo.VisitationsServiceImageEntryRequest\x1a\x1a.Scailo.IdentifierResponse\x12Y\n" +
	"\x0fRecordImageExit\x12*.Scailo.VisitationsServiceImageExitRequest\x1a\x1a.Scailo.IdentifierResponse\x122\n" +
	"\bViewByID\x12\x12.Scailo.Identifier\x1a\x12.Scailo.Visitation\x128\n" +
	"\n" +
	"ViewByUUID\x12\x16.Scailo.IdentifierUUID\x1a\x12.Scailo.Visitation\x12;\n" +
	"\x11ViewEssentialByID\x12\x12.Scailo.Identifier\x1a\x12.Scailo.Visitation\x12A\n" +
	"\x13ViewEssentialByUUID\x12\x16.Scailo.IdentifierUUID\x1a\x12.Scailo.Visitation\x12?\n" +
	"\vViewFromIDs\x12\x17.Scailo.IdentifiersList\x1a\x17.Scailo.VisitationsList\x128\n" +
	"\aViewAll\x12\x14.Scailo.ActiveStatus\x1a\x17.Scailo.VisitationsList\x12G\n" +
	"\x14ViewAllForEntityUUID\x12\x16.Scailo.IdentifierUUID\x1a\x17.Scailo.VisitationsList\x12k\n" +
	"\x12ViewWithPagination\x12'.Scailo.VisitationsServicePaginationReq\x1a,.Scailo.VisitationsServicePaginationResponse\x12?\n" +
	"\x0eViewEntryImage\x12\x16.Scailo.IdentifierUUID\x1a\x15.Scailo.ImageResponse\x12>\n" +
	"\rViewExitImage\x12\x16.Scailo.IdentifierUUID\x1a\x15.Scailo.ImageResponse\x12Q\n" +
	"\x17ViewEntryGPSCoordinates\x12\x16.Scailo.IdentifierUUID\x1a\x1e.Scailo.GPSCoordinatesResponse\x12P\n" +
	"\x16ViewExitGPSCoordinates\x12\x16.Scailo.IdentifierUUID\x1a\x1e.Scailo.GPSCoordinatesResponse\x12H\n" +
	"\x17ViewEntryGPSStaticImage\x12\x16.Scailo.IdentifierUUID\x1a\x15.Scailo.ImageResponse\x12G\n" +
	"\x16ViewExitGPSStaticImage\x12\x16.Scailo.IdentifierUUID\x1a\x15.Scailo.ImageResponse\x12;\n" +
	"\n" +
	"ViewQRCode\x12\x16.Scailo.IdentifierUUID\x1a\x15.Scailo.ImageResponse\x12H\n" +
	"\x1eViewOpenVisitationForAssociate\x12\x12.Scailo.Identifier\x1a\x12.Scailo.Visitation\x12L\n" +
	"\tSearchAll\x12&.Scailo.VisitationsServiceSearchAllReq\x1a\x17.Scailo.VisitationsList\x12F\n" +
	"\x06Filter\x12#.Scailo.VisitationsServiceFilterReq\x1a\x17.Scailo.VisitationsList\x12I\n" +
	"\x1aAssociateHasOpenVisitation\x12\x12.Scailo.Identifier\x1a\x17.Scailo.BooleanResponse\x12G\n" +
	"\rCountInStatus\x12\x1f.Scailo.CountInSLCStatusRequest\x1a\x15.Scailo.CountResponse\x12B\n" +
	"\x05Count\x12\".Scailo.VisitationsServiceCountReq\x1a\x15.Scailo.CountResponse\x12J\n" +
	"\rDownloadAsCSV\x12#.Scailo.VisitationsServiceFilterReq\x1a\x14.Scailo.StandardFileBh\n" +
	"\n" +
	"com.ScailoB\x16VisitationsScailoProtoP\x01Z\n" +
	"Scailo/sdk\xa2\x02\x03SXX\xaa\x02\x06Scailo\xca\x02\x06Scailo\xe2\x02\x12Scailo\\GPBMetadata\xea\x02\x06Scailob\x06proto3"

var (
	file_visitations_scailo_proto_rawDescOnce sync.Once
	file_visitations_scailo_proto_rawDescData []byte
)

func file_visitations_scailo_proto_rawDescGZIP() []byte {
	file_visitations_scailo_proto_rawDescOnce.Do(func() {
		file_visitations_scailo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visitations_scailo_proto_rawDesc), len(file_visitations_scailo_proto_rawDesc)))
	})
	return file_visitations_scailo_proto_rawDescData
}

var file_visitations_scailo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_visitations_scailo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_visitations_scailo_proto_goTypes = []any{
	(VISITATION_SORT_KEY)(0),                                  // 0: Scailo.VISITATION_SORT_KEY
	(*VisitationsServiceCreateRequest)(nil),                   // 1: Scailo.VisitationsServiceCreateRequest
	(*VisitationsServiceUpdateRequest)(nil),                   // 2: Scailo.VisitationsServiceUpdateRequest
	(*VisitationsServiceImageEntryRequest)(nil),               // 3: Scailo.VisitationsServiceImageEntryRequest
	(*VisitationsServiceImageExitRequest)(nil),                // 4: Scailo.VisitationsServiceImageExitRequest
	(*Visitation)(nil),                                        // 5: Scailo.Visitation
	(*VisitationsList)(nil),                                   // 6: Scailo.VisitationsList
	(*VisitationsServicePaginationReq)(nil),                   // 7: Scailo.VisitationsServicePaginationReq
	(*VisitationsServicePaginationResponse)(nil),              // 8: Scailo.VisitationsServicePaginationResponse
	(*VisitationsServiceFilterReq)(nil),                       // 9: Scailo.VisitationsServiceFilterReq
	(*VisitationsServiceCountReq)(nil),                        // 10: Scailo.VisitationsServiceCountReq
	(*VisitationsServiceSearchAllReq)(nil),                    // 11: Scailo.VisitationsServiceSearchAllReq
	(*FormFieldDatumCreateRequest)(nil),                       // 12: Scailo.FormFieldDatumCreateRequest
	(*EmployeeMetadata)(nil),                                  // 13: Scailo.EmployeeMetadata
	(*ApprovalMetadata)(nil),                                  // 14: Scailo.ApprovalMetadata
	(STANDARD_LIFECYCLE_STATUS)(0),                            // 15: Scailo.STANDARD_LIFECYCLE_STATUS
	(*LogbookLogConciseSLC)(nil),                              // 16: Scailo.LogbookLogConciseSLC
	(*FormFieldDatum)(nil),                                    // 17: Scailo.FormFieldDatum
	(BOOL_FILTER)(0),                                          // 18: Scailo.BOOL_FILTER
	(SORT_ORDER)(0),                                           // 19: Scailo.SORT_ORDER
	(*FormFieldDatumFilterRequest)(nil),                       // 20: Scailo.FormFieldDatumFilterRequest
	(*IdentifierUUIDWithUserComment)(nil),                     // 21: Scailo.IdentifierUUIDWithUserComment
	(*MagicLinksServiceCreateRequestForSpecificResource)(nil), // 22: Scailo.MagicLinksServiceCreateRequestForSpecificResource
	(*Identifier)(nil),                                        // 23: Scailo.Identifier
	(*IdentifierUUID)(nil),                                    // 24: Scailo.IdentifierUUID
	(*IdentifiersList)(nil),                                   // 25: Scailo.IdentifiersList
	(*ActiveStatus)(nil),                                      // 26: Scailo.ActiveStatus
	(*CountInSLCStatusRequest)(nil),                           // 27: Scailo.CountInSLCStatusRequest
	(*IdentifierResponse)(nil),                                // 28: Scailo.IdentifierResponse
	(*MagicLink)(nil),                                         // 29: Scailo.MagicLink
	(*ImageResponse)(nil),                                     // 30: Scailo.ImageResponse
	(*GPSCoordinatesResponse)(nil),                            // 31: Scailo.GPSCoordinatesResponse
	(*BooleanResponse)(nil),                                   // 32: Scailo.BooleanResponse
	(*CountResponse)(nil),                                     // 33: Scailo.CountResponse
	(*StandardFile)(nil),                                      // 34: Scailo.StandardFile
}
var file_visitations_scailo_proto_depIdxs = []int32{
	12, // 0: Scailo.VisitationsServiceCreateRequest.form_data:type_name -> Scailo.FormFieldDatumCreateRequest
	12, // 1: Scailo.VisitationsServiceUpdateRequest.form_data:type_name -> Scailo.FormFieldDatumCreateRequest
	13, // 2: Scailo.Visitation.metadata:type_name -> Scailo.EmployeeMetadata
	14, // 3: Scailo.Visitation.approval_metadata:type_name -> Scailo.ApprovalMetadata
	15, // 4: Scailo.Visitation.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	16, // 5: Scailo.Visitation.logs:type_name -> Scailo.LogbookLogConciseSLC
	17, // 6: Scailo.Visitation.form_data:type_name -> Scailo.FormFieldDatum
	5,  // 7: Scailo.VisitationsList.list:type_name -> Scailo.Visitation
	18, // 8: Scailo.VisitationsServicePaginationReq.is_active:type_name -> Scailo.BOOL_FILTER
	19, // 9: Scailo.VisitationsServicePaginationReq.sort_order:type_name -> Scailo.SORT_ORDER
	0,  // 10: Scailo.VisitationsServicePaginationReq.sort_key:type_name -> Scailo.VISITATION_SORT_KEY
	15, // 11: Scailo.VisitationsServicePaginationReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	5,  // 12: Scailo.VisitationsServicePaginationResponse.payload:type_name -> Scailo.Visitation
	18, // 13: Scailo.VisitationsServiceFilterReq.is_active:type_name -> Scailo.BOOL_FILTER
	19, // 14: Scailo.VisitationsServiceFilterReq.sort_order:type_name -> Scailo.SORT_ORDER
	0,  // 15: Scailo.VisitationsServiceFilterReq.sort_key:type_name -> Scailo.VISITATION_SORT_KEY
	15, // 16: Scailo.VisitationsServiceFilterReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	20, // 17: Scailo.VisitationsServiceFilterReq.form_data:type_name -> Scailo.FormFieldDatumFilterRequest
	18, // 18: Scailo.VisitationsServiceCountReq.is_active:type_name -> Scailo.BOOL_FILTER
	15, // 19: Scailo.VisitationsServiceCountReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	20, // 20: Scailo.VisitationsServiceCountReq.form_data:type_name -> Scailo.FormFieldDatumFilterRequest
	18, // 21: Scailo.VisitationsServiceSearchAllReq.is_active:type_name -> Scailo.BOOL_FILTER
	19, // 22: Scailo.VisitationsServiceSearchAllReq.sort_order:type_name -> Scailo.SORT_ORDER
	0,  // 23: Scailo.VisitationsServiceSearchAllReq.sort_key:type_name -> Scailo.VISITATION_SORT_KEY
	15, // 24: Scailo.VisitationsServiceSearchAllReq.status:type_name -> Scailo.STANDARD_LIFECYCLE_STATUS
	1,  // 25: Scailo.VisitationsService.Create:input_type -> Scailo.VisitationsServiceCreateRequest
	1,  // 26: Scailo.VisitationsService.Draft:input_type -> Scailo.VisitationsServiceCreateRequest
	2,  // 27: Scailo.VisitationsService.DraftUpdate:input_type -> Scailo.VisitationsServiceUpdateRequest
	21, // 28: Scailo.VisitationsService.SendForVerification:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 29: Scailo.VisitationsService.Verify:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 30: Scailo.VisitationsService.Approve:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 31: Scailo.VisitationsService.SendForRevision:input_type -> Scailo.IdentifierUUIDWithUserComment
	2,  // 32: Scailo.VisitationsService.RevisionUpdate:input_type -> Scailo.VisitationsServiceUpdateRequest
	21, // 33: Scailo.VisitationsService.Halt:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 34: Scailo.VisitationsService.Discard:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 35: Scailo.VisitationsService.Restore:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 36: Scailo.VisitationsService.Complete:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 37: Scailo.VisitationsService.Repeat:input_type -> Scailo.IdentifierUUIDWithUserComment
	21, // 38: Scailo.VisitationsService.CommentAdd:input_type -> Scailo.IdentifierUUIDWithUserComment
	22, // 39: Scailo.VisitationsService.CreateMagicLink:input_type -> Scailo.MagicLinksServiceCreateRequestForSpecificResource
	3,  // 40: Scailo.VisitationsService.RecordImageEntry:input_type -> Scailo.VisitationsServiceImageEntryRequest
	4,  // 41: Scailo.VisitationsService.RecordImageExit:input_type -> Scailo.VisitationsServiceImageExitRequest
	23, // 42: Scailo.VisitationsService.ViewByID:input_type -> Scailo.Identifier
	24, // 43: Scailo.VisitationsService.ViewByUUID:input_type -> Scailo.IdentifierUUID
	23, // 44: Scailo.VisitationsService.ViewEssentialByID:input_type -> Scailo.Identifier
	24, // 45: Scailo.VisitationsService.ViewEssentialByUUID:input_type -> Scailo.IdentifierUUID
	25, // 46: Scailo.VisitationsService.ViewFromIDs:input_type -> Scailo.IdentifiersList
	26, // 47: Scailo.VisitationsService.ViewAll:input_type -> Scailo.ActiveStatus
	24, // 48: Scailo.VisitationsService.ViewAllForEntityUUID:input_type -> Scailo.IdentifierUUID
	7,  // 49: Scailo.VisitationsService.ViewWithPagination:input_type -> Scailo.VisitationsServicePaginationReq
	24, // 50: Scailo.VisitationsService.ViewEntryImage:input_type -> Scailo.IdentifierUUID
	24, // 51: Scailo.VisitationsService.ViewExitImage:input_type -> Scailo.IdentifierUUID
	24, // 52: Scailo.VisitationsService.ViewEntryGPSCoordinates:input_type -> Scailo.IdentifierUUID
	24, // 53: Scailo.VisitationsService.ViewExitGPSCoordinates:input_type -> Scailo.IdentifierUUID
	24, // 54: Scailo.VisitationsService.ViewEntryGPSStaticImage:input_type -> Scailo.IdentifierUUID
	24, // 55: Scailo.VisitationsService.ViewExitGPSStaticImage:input_type -> Scailo.IdentifierUUID
	24, // 56: Scailo.VisitationsService.ViewQRCode:input_type -> Scailo.IdentifierUUID
	23, // 57: Scailo.VisitationsService.ViewOpenVisitationForAssociate:input_type -> Scailo.Identifier
	11, // 58: Scailo.VisitationsService.SearchAll:input_type -> Scailo.VisitationsServiceSearchAllReq
	9,  // 59: Scailo.VisitationsService.Filter:input_type -> Scailo.VisitationsServiceFilterReq
	23, // 60: Scailo.VisitationsService.AssociateHasOpenVisitation:input_type -> Scailo.Identifier
	27, // 61: Scailo.VisitationsService.CountInStatus:input_type -> Scailo.CountInSLCStatusRequest
	10, // 62: Scailo.VisitationsService.Count:input_type -> Scailo.VisitationsServiceCountReq
	9,  // 63: Scailo.VisitationsService.DownloadAsCSV:input_type -> Scailo.VisitationsServiceFilterReq
	28, // 64: Scailo.VisitationsService.Create:output_type -> Scailo.IdentifierResponse
	28, // 65: Scailo.VisitationsService.Draft:output_type -> Scailo.IdentifierResponse
	28, // 66: Scailo.VisitationsService.DraftUpdate:output_type -> Scailo.IdentifierResponse
	28, // 67: Scailo.VisitationsService.SendForVerification:output_type -> Scailo.IdentifierResponse
	28, // 68: Scailo.VisitationsService.Verify:output_type -> Scailo.IdentifierResponse
	28, // 69: Scailo.VisitationsService.Approve:output_type -> Scailo.IdentifierResponse
	28, // 70: Scailo.VisitationsService.SendForRevision:output_type -> Scailo.IdentifierResponse
	28, // 71: Scailo.VisitationsService.RevisionUpdate:output_type -> Scailo.IdentifierResponse
	28, // 72: Scailo.VisitationsService.Halt:output_type -> Scailo.IdentifierResponse
	28, // 73: Scailo.VisitationsService.Discard:output_type -> Scailo.IdentifierResponse
	28, // 74: Scailo.VisitationsService.Restore:output_type -> Scailo.IdentifierResponse
	28, // 75: Scailo.VisitationsService.Complete:output_type -> Scailo.IdentifierResponse
	28, // 76: Scailo.VisitationsService.Repeat:output_type -> Scailo.IdentifierResponse
	28, // 77: Scailo.VisitationsService.CommentAdd:output_type -> Scailo.IdentifierResponse
	29, // 78: Scailo.VisitationsService.CreateMagicLink:output_type -> Scailo.MagicLink
	28, // 79: Scailo.VisitationsService.RecordImageEntry:output_type -> Scailo.IdentifierResponse
	28, // 80: Scailo.VisitationsService.RecordImageExit:output_type -> Scailo.IdentifierResponse
	5,  // 81: Scailo.VisitationsService.ViewByID:output_type -> Scailo.Visitation
	5,  // 82: Scailo.VisitationsService.ViewByUUID:output_type -> Scailo.Visitation
	5,  // 83: Scailo.VisitationsService.ViewEssentialByID:output_type -> Scailo.Visitation
	5,  // 84: Scailo.VisitationsService.ViewEssentialByUUID:output_type -> Scailo.Visitation
	6,  // 85: Scailo.VisitationsService.ViewFromIDs:output_type -> Scailo.VisitationsList
	6,  // 86: Scailo.VisitationsService.ViewAll:output_type -> Scailo.VisitationsList
	6,  // 87: Scailo.VisitationsService.ViewAllForEntityUUID:output_type -> Scailo.VisitationsList
	8,  // 88: Scailo.VisitationsService.ViewWithPagination:output_type -> Scailo.VisitationsServicePaginationResponse
	30, // 89: Scailo.VisitationsService.ViewEntryImage:output_type -> Scailo.ImageResponse
	30, // 90: Scailo.VisitationsService.ViewExitImage:output_type -> Scailo.ImageResponse
	31, // 91: Scailo.VisitationsService.ViewEntryGPSCoordinates:output_type -> Scailo.GPSCoordinatesResponse
	31, // 92: Scailo.VisitationsService.ViewExitGPSCoordinates:output_type -> Scailo.GPSCoordinatesResponse
	30, // 93: Scailo.VisitationsService.ViewEntryGPSStaticImage:output_type -> Scailo.ImageResponse
	30, // 94: Scailo.VisitationsService.ViewExitGPSStaticImage:output_type -> Scailo.ImageResponse
	30, // 95: Scailo.VisitationsService.ViewQRCode:output_type -> Scailo.ImageResponse
	5,  // 96: Scailo.VisitationsService.ViewOpenVisitationForAssociate:output_type -> Scailo.Visitation
	6,  // 97: Scailo.VisitationsService.SearchAll:output_type -> Scailo.VisitationsList
	6,  // 98: Scailo.VisitationsService.Filter:output_type -> Scailo.VisitationsList
	32, // 99: Scailo.VisitationsService.AssociateHasOpenVisitation:output_type -> Scailo.BooleanResponse
	33, // 100: Scailo.VisitationsService.CountInStatus:output_type -> Scailo.CountResponse
	33, // 101: Scailo.VisitationsService.Count:output_type -> Scailo.CountResponse
	34, // 102: Scailo.VisitationsService.DownloadAsCSV:output_type -> Scailo.StandardFile
	64, // [64:103] is the sub-list for method output_type
	25, // [25:64] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_visitations_scailo_proto_init() }
func file_visitations_scailo_proto_init() {
	if File_visitations_scailo_proto != nil {
		return
	}
	file_base_scailo_proto_init()
	file_forms_fields_data_scailo_proto_init()
	file_magic_links_scailo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visitations_scailo_proto_rawDesc), len(file_visitations_scailo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_visitations_scailo_proto_goTypes,
		DependencyIndexes: file_visitations_scailo_proto_depIdxs,
		EnumInfos:         file_visitations_scailo_proto_enumTypes,
		MessageInfos:      file_visitations_scailo_proto_msgTypes,
	}.Build()
	File_visitations_scailo_proto = out.File
	file_visitations_scailo_proto_goTypes = nil
	file_visitations_scailo_proto_depIdxs = nil
}
